/*** Autogenerated by WIDL 10.9 from windows.media.protection.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_media_protection_h__
#define __windows_media_protection_h__

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionManager_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionManager_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                class MediaProtectionManager;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CMediaProtectionManager __x_ABI_CWindows_CMedia_CProtection_CMediaProtectionManager;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionManager_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionPMPServer_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionPMPServer_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                class MediaProtectionPMPServer;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CMediaProtectionPMPServer __x_ABI_CWindows_CMedia_CProtection_CMediaProtectionPMPServer;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_CProtection_CMediaProtectionPMPServer_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CComponentLoadFailedEventArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CComponentLoadFailedEventArgs_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                class ComponentLoadFailedEventArgs;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CComponentLoadFailedEventArgs __x_ABI_CWindows_CMedia_CProtection_CComponentLoadFailedEventArgs;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_CProtection_CComponentLoadFailedEventArgs_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CServiceRequestedEventArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CServiceRequestedEventArgs_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                class ServiceRequestedEventArgs;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CServiceRequestedEventArgs __x_ABI_CWindows_CMedia_CProtection_CServiceRequestedEventArgs;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_CProtection_CServiceRequestedEventArgs_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler ABI::Windows::Media::Protection::IComponentLoadFailedEventHandler
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IComponentLoadFailedEventHandler;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler ABI::Windows::Media::Protection::IRebootNeededEventHandler
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IRebootNeededEventHandler;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler ABI::Windows::Media::Protection::IServiceRequestedEventHandler
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IServiceRequestedEventHandler;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager ABI::Windows::Media::Protection::IMediaProtectionManager
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionManager;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest ABI::Windows::Media::Protection::IMediaProtectionServiceRequest
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionServiceRequest;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer ABI::Windows::Media::Protection::IMediaProtectionPMPServer
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionPMPServer;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager ABI::Windows::Media::Protection::IMediaProtectionManager
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionManager;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest ABI::Windows::Media::Protection::IMediaProtectionServiceRequest
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionServiceRequest;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer ABI::Windows::Media::Protection::IMediaProtectionPMPServer
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionPMPServer;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs ABI::Windows::Media::Protection::IComponentLoadFailedEventArgs
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IComponentLoadFailedEventArgs;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs ABI::Windows::Media::Protection::IServiceRequestedEventArgs
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IServiceRequestedEventArgs;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager ABI::Windows::Media::Protection::IMediaProtectionManager
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionManager;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest ABI::Windows::Media::Protection::IMediaProtectionServiceRequest
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionServiceRequest;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer ABI::Windows::Media::Protection::IMediaProtectionPMPServer
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                interface IMediaProtectionPMPServer;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/*
 * Class Windows.Media.Protection.MediaProtectionManager
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Protection_MediaProtectionManager_DEFINED
#define RUNTIMECLASS_Windows_Media_Protection_MediaProtectionManager_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionManager[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','M','e','d','i','a','P','r','o','t','e','c','t','i','o','n','M','a','n','a','g','e','r',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionManager[] = L"Windows.Media.Protection.MediaProtectionManager";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionManager[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','M','e','d','i','a','P','r','o','t','e','c','t','i','o','n','M','a','n','a','g','e','r',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Protection_MediaProtectionManager_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Protection.MediaProtectionPMPServer
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Protection_MediaProtectionPMPServer_DEFINED
#define RUNTIMECLASS_Windows_Media_Protection_MediaProtectionPMPServer_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionPMPServer[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','M','e','d','i','a','P','r','o','t','e','c','t','i','o','n','P','M','P','S','e','r','v','e','r',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionPMPServer[] = L"Windows.Media.Protection.MediaProtectionPMPServer";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_MediaProtectionPMPServer[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','M','e','d','i','a','P','r','o','t','e','c','t','i','o','n','P','M','P','S','e','r','v','e','r',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Protection_MediaProtectionPMPServer_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Protection.ComponentLoadFailedEventArgs
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Protection_ComponentLoadFailedEventArgs_DEFINED
#define RUNTIMECLASS_Windows_Media_Protection_ComponentLoadFailedEventArgs_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Protection_ComponentLoadFailedEventArgs[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','C','o','m','p','o','n','e','n','t','L','o','a','d','F','a','i','l','e','d','E','v','e','n','t','A','r','g','s',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_ComponentLoadFailedEventArgs[] = L"Windows.Media.Protection.ComponentLoadFailedEventArgs";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_ComponentLoadFailedEventArgs[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','C','o','m','p','o','n','e','n','t','L','o','a','d','F','a','i','l','e','d','E','v','e','n','t','A','r','g','s',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Protection_ComponentLoadFailedEventArgs_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Protection.ServiceRequestedEventArgs
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Protection_ServiceRequestedEventArgs_DEFINED
#define RUNTIMECLASS_Windows_Media_Protection_ServiceRequestedEventArgs_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Protection_ServiceRequestedEventArgs[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','S','e','r','v','i','c','e','R','e','q','u','e','s','t','e','d','E','v','e','n','t','A','r','g','s',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_ServiceRequestedEventArgs[] = L"Windows.Media.Protection.ServiceRequestedEventArgs";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Protection_ServiceRequestedEventArgs[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','P','r','o','t','e','c','t','i','o','n','.','S','e','r','v','i','c','e','R','e','q','u','e','s','t','e','d','E','v','e','n','t','A','r','g','s',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Protection_ServiceRequestedEventArgs_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IComponentLoadFailedEventHandler interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler, 0x95da643c, 0x6db9, 0x424b, 0x86,0xca, 0x09,0x1a,0xf4,0x32,0x08,0x1c);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("95da643c-6db9-424b-86ca-091af432081c")
                IComponentLoadFailedEventHandler : public IUnknown
                {
                    virtual HRESULT STDMETHODCALLTYPE Invoke(
                        ABI::Windows::Media::Protection::IMediaProtectionManager *sender,
                        ABI::Windows::Media::Protection::IComponentLoadFailedEventArgs *e) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler, 0x95da643c, 0x6db9, 0x424b, 0x86,0xca, 0x09,0x1a,0xf4,0x32,0x08,0x1c)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandlerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *This);

    /*** IComponentLoadFailedEventHandler methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *This,
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender,
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs *e);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandlerVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandlerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Release(This) (This)->lpVtbl->Release(This)
/*** IComponentLoadFailedEventHandler methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Invoke(This,sender,e) (This)->lpVtbl->Invoke(This,sender,e)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Release(__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler* This) {
    return This->lpVtbl->Release(This);
}
/*** IComponentLoadFailedEventHandler methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Invoke(__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler* This,__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender,__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventArgs *e) {
    return This->lpVtbl->Invoke(This,sender,e);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IComponentLoadFailedEventHandler IID___x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler
#define IComponentLoadFailedEventHandlerVtbl __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandlerVtbl
#define IComponentLoadFailedEventHandler __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler
#define IComponentLoadFailedEventHandler_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_QueryInterface
#define IComponentLoadFailedEventHandler_AddRef __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_AddRef
#define IComponentLoadFailedEventHandler_Release __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Release
#define IComponentLoadFailedEventHandler_Invoke __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_Invoke
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IRebootNeededEventHandler interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler, 0x64e12a45, 0x973b, 0x4a3a, 0xb2,0x60, 0x91,0x89,0x8a,0x49,0xa8,0x2c);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("64e12a45-973b-4a3a-b260-91898a49a82c")
                IRebootNeededEventHandler : public IUnknown
                {
                    virtual HRESULT STDMETHODCALLTYPE Invoke(
                        ABI::Windows::Media::Protection::IMediaProtectionManager *sender) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler, 0x64e12a45, 0x973b, 0x4a3a, 0xb2,0x60, 0x91,0x89,0x8a,0x49,0xa8,0x2c)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandlerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *This);

    /*** IRebootNeededEventHandler methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *This,
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandlerVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandlerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Release(This) (This)->lpVtbl->Release(This)
/*** IRebootNeededEventHandler methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Invoke(This,sender) (This)->lpVtbl->Invoke(This,sender)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Release(__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler* This) {
    return This->lpVtbl->Release(This);
}
/*** IRebootNeededEventHandler methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Invoke(__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler* This,__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender) {
    return This->lpVtbl->Invoke(This,sender);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IRebootNeededEventHandler IID___x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler
#define IRebootNeededEventHandlerVtbl __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandlerVtbl
#define IRebootNeededEventHandler __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler
#define IRebootNeededEventHandler_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_QueryInterface
#define IRebootNeededEventHandler_AddRef __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_AddRef
#define IRebootNeededEventHandler_Release __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Release
#define IRebootNeededEventHandler_Invoke __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_Invoke
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IServiceRequestedEventHandler interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler, 0xd2d690ba, 0xcac9, 0x48e1, 0x95,0xc0, 0xd3,0x84,0x95,0xa8,0x40,0x55);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("d2d690ba-cac9-48e1-95c0-d38495a84055")
                IServiceRequestedEventHandler : public IUnknown
                {
                    virtual HRESULT STDMETHODCALLTYPE Invoke(
                        ABI::Windows::Media::Protection::IMediaProtectionManager *sender,
                        ABI::Windows::Media::Protection::IServiceRequestedEventArgs *e) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler, 0xd2d690ba, 0xcac9, 0x48e1, 0x95,0xc0, 0xd3,0x84,0x95,0xa8,0x40,0x55)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandlerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *This);

    /*** IServiceRequestedEventHandler methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *This,
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender,
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs *e);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandlerVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandlerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Release(This) (This)->lpVtbl->Release(This)
/*** IServiceRequestedEventHandler methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Invoke(This,sender,e) (This)->lpVtbl->Invoke(This,sender,e)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Release(__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler* This) {
    return This->lpVtbl->Release(This);
}
/*** IServiceRequestedEventHandler methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Invoke(__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler* This,__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *sender,__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventArgs *e) {
    return This->lpVtbl->Invoke(This,sender,e);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IServiceRequestedEventHandler IID___x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler
#define IServiceRequestedEventHandlerVtbl __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandlerVtbl
#define IServiceRequestedEventHandler __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler
#define IServiceRequestedEventHandler_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_QueryInterface
#define IServiceRequestedEventHandler_AddRef __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_AddRef
#define IServiceRequestedEventHandler_Release __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Release
#define IServiceRequestedEventHandler_Invoke __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_Invoke
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IMediaProtectionManager interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager, 0x45694947, 0xc741, 0x434b, 0xa7,0x9e, 0x47,0x4c,0x12,0xd9,0x3d,0x2f);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("45694947-c741-434b-a79e-474c12d93d2f")
                IMediaProtectionManager : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE add_ServiceRequested(
                        ABI::Windows::Media::Protection::IServiceRequestedEventHandler *handler,
                        EventRegistrationToken *cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE remove_ServiceRequested(
                        EventRegistrationToken cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE add_RebootNeeded(
                        ABI::Windows::Media::Protection::IRebootNeededEventHandler *handler,
                        EventRegistrationToken *cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE remove_RebootNeeded(
                        EventRegistrationToken cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE add_ComponentLoadFailed(
                        ABI::Windows::Media::Protection::IComponentLoadFailedEventHandler *handler,
                        EventRegistrationToken *cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE remove_ComponentLoadFailed(
                        EventRegistrationToken cookie) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Properties(
                        ABI::Windows::Foundation::Collections::IPropertySet **value) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager, 0x45694947, 0xc741, 0x434b, 0xa7,0x9e, 0x47,0x4c,0x12,0xd9,0x3d,0x2f)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManagerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        TrustLevel *trustLevel);

    /*** IMediaProtectionManager methods ***/
    HRESULT (STDMETHODCALLTYPE *add_ServiceRequested)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        __x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *handler,
        EventRegistrationToken *cookie);

    HRESULT (STDMETHODCALLTYPE *remove_ServiceRequested)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        EventRegistrationToken cookie);

    HRESULT (STDMETHODCALLTYPE *add_RebootNeeded)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        __x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *handler,
        EventRegistrationToken *cookie);

    HRESULT (STDMETHODCALLTYPE *remove_RebootNeeded)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        EventRegistrationToken cookie);

    HRESULT (STDMETHODCALLTYPE *add_ComponentLoadFailed)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        __x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *handler,
        EventRegistrationToken *cookie);

    HRESULT (STDMETHODCALLTYPE *remove_ComponentLoadFailed)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        EventRegistrationToken cookie);

    HRESULT (STDMETHODCALLTYPE *get_Properties)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager *This,
        __x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **value);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManagerVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManagerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IMediaProtectionManager methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ServiceRequested(This,handler,cookie) (This)->lpVtbl->add_ServiceRequested(This,handler,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ServiceRequested(This,cookie) (This)->lpVtbl->remove_ServiceRequested(This,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_RebootNeeded(This,handler,cookie) (This)->lpVtbl->add_RebootNeeded(This,handler,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_RebootNeeded(This,cookie) (This)->lpVtbl->remove_RebootNeeded(This,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ComponentLoadFailed(This,handler,cookie) (This)->lpVtbl->add_ComponentLoadFailed(This,handler,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ComponentLoadFailed(This,cookie) (This)->lpVtbl->remove_ComponentLoadFailed(This,cookie)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_get_Properties(This,value) (This)->lpVtbl->get_Properties(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_Release(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetIids(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetRuntimeClassName(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetTrustLevel(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IMediaProtectionManager methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ServiceRequested(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,__x_ABI_CWindows_CMedia_CProtection_CIServiceRequestedEventHandler *handler,EventRegistrationToken *cookie) {
    return This->lpVtbl->add_ServiceRequested(This,handler,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ServiceRequested(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,EventRegistrationToken cookie) {
    return This->lpVtbl->remove_ServiceRequested(This,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_RebootNeeded(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,__x_ABI_CWindows_CMedia_CProtection_CIRebootNeededEventHandler *handler,EventRegistrationToken *cookie) {
    return This->lpVtbl->add_RebootNeeded(This,handler,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_RebootNeeded(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,EventRegistrationToken cookie) {
    return This->lpVtbl->remove_RebootNeeded(This,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ComponentLoadFailed(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,__x_ABI_CWindows_CMedia_CProtection_CIComponentLoadFailedEventHandler *handler,EventRegistrationToken *cookie) {
    return This->lpVtbl->add_ComponentLoadFailed(This,handler,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ComponentLoadFailed(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,EventRegistrationToken cookie) {
    return This->lpVtbl->remove_ComponentLoadFailed(This,cookie);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_get_Properties(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager* This,__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **value) {
    return This->lpVtbl->get_Properties(This,value);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IMediaProtectionManager IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager
#define IMediaProtectionManagerVtbl __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManagerVtbl
#define IMediaProtectionManager __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager
#define IMediaProtectionManager_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_QueryInterface
#define IMediaProtectionManager_AddRef __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_AddRef
#define IMediaProtectionManager_Release __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_Release
#define IMediaProtectionManager_GetIids __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetIids
#define IMediaProtectionManager_GetRuntimeClassName __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetRuntimeClassName
#define IMediaProtectionManager_GetTrustLevel __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_GetTrustLevel
#define IMediaProtectionManager_add_ServiceRequested __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ServiceRequested
#define IMediaProtectionManager_remove_ServiceRequested __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ServiceRequested
#define IMediaProtectionManager_add_RebootNeeded __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_RebootNeeded
#define IMediaProtectionManager_remove_RebootNeeded __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_RebootNeeded
#define IMediaProtectionManager_add_ComponentLoadFailed __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_add_ComponentLoadFailed
#define IMediaProtectionManager_remove_ComponentLoadFailed __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_remove_ComponentLoadFailed
#define IMediaProtectionManager_get_Properties __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_get_Properties
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionManager_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IMediaProtectionServiceRequest interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest, 0xb1de0ea6, 0x2094, 0x478d, 0x87,0xa4, 0x8b,0x95,0x20,0x0f,0x85,0xc6);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("b1de0ea6-2094-478d-87a4-8b95200f85c6")
                IMediaProtectionServiceRequest : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_ProtectionSystem(
                        GUID *system) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Type(
                        GUID *type) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest, 0xb1de0ea6, 0x2094, 0x478d, 0x87,0xa4, 0x8b,0x95,0x20,0x0f,0x85,0xc6)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequestVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        TrustLevel *trustLevel);

    /*** IMediaProtectionServiceRequest methods ***/
    HRESULT (STDMETHODCALLTYPE *get_ProtectionSystem)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        GUID *system);

    HRESULT (STDMETHODCALLTYPE *get_Type)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest *This,
        GUID *type);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequestVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequestVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IMediaProtectionServiceRequest methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_ProtectionSystem(This,system) (This)->lpVtbl->get_ProtectionSystem(This,system)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_Type(This,type) (This)->lpVtbl->get_Type(This,type)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_Release(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetIids(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetRuntimeClassName(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetTrustLevel(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IMediaProtectionServiceRequest methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_ProtectionSystem(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,GUID *system) {
    return This->lpVtbl->get_ProtectionSystem(This,system);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_Type(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest* This,GUID *type) {
    return This->lpVtbl->get_Type(This,type);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IMediaProtectionServiceRequest IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest
#define IMediaProtectionServiceRequestVtbl __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequestVtbl
#define IMediaProtectionServiceRequest __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest
#define IMediaProtectionServiceRequest_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_QueryInterface
#define IMediaProtectionServiceRequest_AddRef __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_AddRef
#define IMediaProtectionServiceRequest_Release __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_Release
#define IMediaProtectionServiceRequest_GetIids __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetIids
#define IMediaProtectionServiceRequest_GetRuntimeClassName __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetRuntimeClassName
#define IMediaProtectionServiceRequest_GetTrustLevel __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_GetTrustLevel
#define IMediaProtectionServiceRequest_get_ProtectionSystem __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_ProtectionSystem
#define IMediaProtectionServiceRequest_get_Type __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_get_Type
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionServiceRequest_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IMediaProtectionPMPServer interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer, 0x0c111226, 0x7b26, 0x4d31, 0x95,0xbb, 0x9c,0x1b,0x08,0xef,0x7f,0xc0);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Protection {
                MIDL_INTERFACE("0c111226-7b26-4d31-95bb-9c1b08ef7fc0")
                IMediaProtectionPMPServer : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_Properties(
                        ABI::Windows::Foundation::Collections::IPropertySet **ppProperties) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer, 0x0c111226, 0x7b26, 0x4d31, 0x95,0xbb, 0x9c,0x1b,0x08,0xef,0x7f,0xc0)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServerVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This,
        TrustLevel *trustLevel);

    /*** IMediaProtectionPMPServer methods ***/
    HRESULT (STDMETHODCALLTYPE *get_Properties)(
        __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer *This,
        __x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **ppProperties);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServerVtbl;

interface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer {
    CONST_VTBL __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServerVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IMediaProtectionPMPServer methods ***/
#define __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_get_Properties(This,ppProperties) (This)->lpVtbl->get_Properties(This,ppProperties)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_QueryInterface(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_AddRef(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_Release(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetIids(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetRuntimeClassName(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetTrustLevel(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IMediaProtectionPMPServer methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_get_Properties(__x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer* This,__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **ppProperties) {
    return This->lpVtbl->get_Properties(This,ppProperties);
}
#endif
#ifdef WIDL_using_Windows_Media_Protection
#define IID_IMediaProtectionPMPServer IID___x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer
#define IMediaProtectionPMPServerVtbl __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServerVtbl
#define IMediaProtectionPMPServer __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer
#define IMediaProtectionPMPServer_QueryInterface __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_QueryInterface
#define IMediaProtectionPMPServer_AddRef __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_AddRef
#define IMediaProtectionPMPServer_Release __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_Release
#define IMediaProtectionPMPServer_GetIids __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetIids
#define IMediaProtectionPMPServer_GetRuntimeClassName __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetRuntimeClassName
#define IMediaProtectionPMPServer_GetTrustLevel __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_GetTrustLevel
#define IMediaProtectionPMPServer_get_Properties __x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_get_Properties
#endif /* WIDL_using_Windows_Media_Protection */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_CProtection_CIMediaProtectionPMPServer_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __windows_media_protection_h__ */
