/*** Autogenerated by WIDL 10.9 from windows.media.ocr.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_media_ocr_h__
#define __windows_media_ocr_h__

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CMedia_COcr_COcrWord_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_COcrWord_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                class OcrWord;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_COcrWord __x_ABI_CWindows_CMedia_COcr_COcrWord;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_COcr_COcrWord_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_COcr_COcrLine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_COcrLine_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                class OcrLine;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_COcrLine __x_ABI_CWindows_CMedia_COcr_COcrLine;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_COcr_COcrLine_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_COcr_COcrResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_COcrResult_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                class OcrResult;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_COcrResult __x_ABI_CWindows_CMedia_COcr_COcrResult;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_COcr_COcrResult_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_COcr_COcrEngine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_COcrEngine_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                class OcrEngine;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_COcrEngine __x_ABI_CWindows_CMedia_COcr_COcrEngine;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CMedia_COcr_COcrEngine_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrWord __x_ABI_CWindows_CMedia_COcr_CIOcrWord;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord ABI::Windows::Media::Ocr::IOcrWord
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrWord;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrLine __x_ABI_CWindows_CMedia_COcr_CIOcrLine;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine ABI::Windows::Media::Ocr::IOcrLine
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrLine;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrResult __x_ABI_CWindows_CMedia_COcr_CIOcrResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult ABI::Windows::Media::Ocr::IOcrResult
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrResult;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngine __x_ABI_CWindows_CMedia_COcr_CIOcrEngine;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine ABI::Windows::Media::Ocr::IOcrEngine
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrEngine;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics ABI::Windows::Media::Ocr::IOcrEngineStatics
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrEngineStatics;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
typedef interface __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult;
#ifdef __cplusplus
#define __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult ABI::Windows::Foundation::IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
#define ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult;
#ifdef __cplusplus
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_FWD_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_FWD_DEFINED__
typedef interface __FIVectorView_1_Windows__CMedia__COcr__COcrLine __FIVectorView_1_Windows__CMedia__COcr__COcrLine;
#ifdef __cplusplus
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrLine* >
#endif /* __cplusplus */
#endif

#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_FWD_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_FWD_DEFINED__
typedef interface __FIVectorView_1_Windows__CMedia__COcr__COcrWord __FIVectorView_1_Windows__CMedia__COcr__COcrWord;
#ifdef __cplusplus
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrWord* >
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>
#include <windows.globalization.h>
#include <windows.graphics.imaging.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrLine __x_ABI_CWindows_CMedia_COcr_CIOcrLine;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine ABI::Windows::Media::Ocr::IOcrLine
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrLine;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrWord __x_ABI_CWindows_CMedia_COcr_CIOcrWord;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord ABI::Windows::Media::Ocr::IOcrWord
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrWord;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrResult __x_ABI_CWindows_CMedia_COcr_CIOcrResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult ABI::Windows::Media::Ocr::IOcrResult
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrResult;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrWord __x_ABI_CWindows_CMedia_COcr_CIOcrWord;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord ABI::Windows::Media::Ocr::IOcrWord
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrWord;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrLine __x_ABI_CWindows_CMedia_COcr_CIOcrLine;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine ABI::Windows::Media::Ocr::IOcrLine
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrLine;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrResult __x_ABI_CWindows_CMedia_COcr_CIOcrResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult ABI::Windows::Media::Ocr::IOcrResult
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrResult;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngine __x_ABI_CWindows_CMedia_COcr_CIOcrEngine;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine ABI::Windows::Media::Ocr::IOcrEngine
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrEngine;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics;
#ifdef __cplusplus
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics ABI::Windows::Media::Ocr::IOcrEngineStatics
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                interface IOcrEngineStatics;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/*
 * Class Windows.Media.Ocr.OcrWord
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Ocr_OcrWord_DEFINED
#define RUNTIMECLASS_Windows_Media_Ocr_OcrWord_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Ocr_OcrWord[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','W','o','r','d',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrWord[] = L"Windows.Media.Ocr.OcrWord";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrWord[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','W','o','r','d',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Ocr_OcrWord_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Ocr.OcrLine
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Ocr_OcrLine_DEFINED
#define RUNTIMECLASS_Windows_Media_Ocr_OcrLine_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Ocr_OcrLine[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','L','i','n','e',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrLine[] = L"Windows.Media.Ocr.OcrLine";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrLine[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','L','i','n','e',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Ocr_OcrLine_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Ocr.OcrResult
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Ocr_OcrResult_DEFINED
#define RUNTIMECLASS_Windows_Media_Ocr_OcrResult_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Ocr_OcrResult[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','R','e','s','u','l','t',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrResult[] = L"Windows.Media.Ocr.OcrResult";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrResult[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','R','e','s','u','l','t',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Ocr_OcrResult_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Media.Ocr.OcrEngine
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Media_Ocr_OcrEngine_DEFINED
#define RUNTIMECLASS_Windows_Media_Ocr_OcrEngine_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Media_Ocr_OcrEngine[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','E','n','g','i','n','e',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrEngine[] = L"Windows.Media.Ocr.OcrEngine";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Media_Ocr_OcrEngine[] = {'W','i','n','d','o','w','s','.','M','e','d','i','a','.','O','c','r','.','O','c','r','E','n','g','i','n','e',0};
#endif
#endif /* RUNTIMECLASS_Windows_Media_Ocr_OcrEngine_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

#ifndef ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
#define ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult;
#ifdef __cplusplus
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_FWD_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_FWD_DEFINED__
typedef interface __FIVectorView_1_Windows__CMedia__COcr__COcrLine __FIVectorView_1_Windows__CMedia__COcr__COcrLine;
#ifdef __cplusplus
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrLine* >
#endif /* __cplusplus */
#endif

#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_FWD_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_FWD_DEFINED__
typedef interface __FIVectorView_1_Windows__CMedia__COcr__COcrWord __FIVectorView_1_Windows__CMedia__COcr__COcrWord;
#ifdef __cplusplus
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrWord* >
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * IOcrWord interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_COcr_CIOcrWord, 0x3c2a477a, 0x5cd9, 0x3525, 0xba,0x2a, 0x23,0xd1,0xe0,0xa6,0x8a,0x1d);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                MIDL_INTERFACE("3c2a477a-5cd9-3525-ba2a-23d1e0a68a1d")
                IOcrWord : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_BoundingRect(
                        ABI::Windows::Foundation::Rect *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Text(
                        HSTRING *value) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_COcr_CIOcrWord, 0x3c2a477a, 0x5cd9, 0x3525, 0xba,0x2a, 0x23,0xd1,0xe0,0xa6,0x8a,0x1d)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_CIOcrWordVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        TrustLevel *trustLevel);

    /*** IOcrWord methods ***/
    HRESULT (STDMETHODCALLTYPE *get_BoundingRect)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        __x_ABI_CWindows_CFoundation_CRect *value);

    HRESULT (STDMETHODCALLTYPE *get_Text)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *This,
        HSTRING *value);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_COcr_CIOcrWordVtbl;

interface __x_ABI_CWindows_CMedia_COcr_CIOcrWord {
    CONST_VTBL __x_ABI_CWindows_CMedia_COcr_CIOcrWordVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IOcrWord methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_BoundingRect(This,value) (This)->lpVtbl->get_BoundingRect(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_Text(This,value) (This)->lpVtbl->get_Text(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_QueryInterface(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrWord_AddRef(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrWord_Release(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetIids(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetRuntimeClassName(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetTrustLevel(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IOcrWord methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_BoundingRect(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,__x_ABI_CWindows_CFoundation_CRect *value) {
    return This->lpVtbl->get_BoundingRect(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_Text(__x_ABI_CWindows_CMedia_COcr_CIOcrWord* This,HSTRING *value) {
    return This->lpVtbl->get_Text(This,value);
}
#endif
#ifdef WIDL_using_Windows_Media_Ocr
#define IID_IOcrWord IID___x_ABI_CWindows_CMedia_COcr_CIOcrWord
#define IOcrWordVtbl __x_ABI_CWindows_CMedia_COcr_CIOcrWordVtbl
#define IOcrWord __x_ABI_CWindows_CMedia_COcr_CIOcrWord
#define IOcrWord_QueryInterface __x_ABI_CWindows_CMedia_COcr_CIOcrWord_QueryInterface
#define IOcrWord_AddRef __x_ABI_CWindows_CMedia_COcr_CIOcrWord_AddRef
#define IOcrWord_Release __x_ABI_CWindows_CMedia_COcr_CIOcrWord_Release
#define IOcrWord_GetIids __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetIids
#define IOcrWord_GetRuntimeClassName __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetRuntimeClassName
#define IOcrWord_GetTrustLevel __x_ABI_CWindows_CMedia_COcr_CIOcrWord_GetTrustLevel
#define IOcrWord_get_BoundingRect __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_BoundingRect
#define IOcrWord_get_Text __x_ABI_CWindows_CMedia_COcr_CIOcrWord_get_Text
#endif /* WIDL_using_Windows_Media_Ocr */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_COcr_CIOcrWord_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IOcrLine interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_COcr_CIOcrLine, 0x0043a16f, 0xe31f, 0x3a24, 0x89,0x9c, 0xd4,0x44,0xbd,0x08,0x81,0x24);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                MIDL_INTERFACE("0043a16f-e31f-3a24-899c-d444bd088124")
                IOcrLine : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_Words(
                        ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrWord* > **value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Text(
                        HSTRING *value) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_COcr_CIOcrLine, 0x0043a16f, 0xe31f, 0x3a24, 0x89,0x9c, 0xd4,0x44,0xbd,0x08,0x81,0x24)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_CIOcrLineVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        TrustLevel *trustLevel);

    /*** IOcrLine methods ***/
    HRESULT (STDMETHODCALLTYPE *get_Words)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord **value);

    HRESULT (STDMETHODCALLTYPE *get_Text)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *This,
        HSTRING *value);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_COcr_CIOcrLineVtbl;

interface __x_ABI_CWindows_CMedia_COcr_CIOcrLine {
    CONST_VTBL __x_ABI_CWindows_CMedia_COcr_CIOcrLineVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IOcrLine methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Words(This,value) (This)->lpVtbl->get_Words(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Text(This,value) (This)->lpVtbl->get_Text(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_QueryInterface(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrLine_AddRef(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrLine_Release(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetIids(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetRuntimeClassName(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetTrustLevel(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IOcrLine methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Words(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,__FIVectorView_1_Windows__CMedia__COcr__COcrWord **value) {
    return This->lpVtbl->get_Words(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Text(__x_ABI_CWindows_CMedia_COcr_CIOcrLine* This,HSTRING *value) {
    return This->lpVtbl->get_Text(This,value);
}
#endif
#ifdef WIDL_using_Windows_Media_Ocr
#define IID_IOcrLine IID___x_ABI_CWindows_CMedia_COcr_CIOcrLine
#define IOcrLineVtbl __x_ABI_CWindows_CMedia_COcr_CIOcrLineVtbl
#define IOcrLine __x_ABI_CWindows_CMedia_COcr_CIOcrLine
#define IOcrLine_QueryInterface __x_ABI_CWindows_CMedia_COcr_CIOcrLine_QueryInterface
#define IOcrLine_AddRef __x_ABI_CWindows_CMedia_COcr_CIOcrLine_AddRef
#define IOcrLine_Release __x_ABI_CWindows_CMedia_COcr_CIOcrLine_Release
#define IOcrLine_GetIids __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetIids
#define IOcrLine_GetRuntimeClassName __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetRuntimeClassName
#define IOcrLine_GetTrustLevel __x_ABI_CWindows_CMedia_COcr_CIOcrLine_GetTrustLevel
#define IOcrLine_get_Words __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Words
#define IOcrLine_get_Text __x_ABI_CWindows_CMedia_COcr_CIOcrLine_get_Text
#endif /* WIDL_using_Windows_Media_Ocr */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_COcr_CIOcrLine_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IOcrResult interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_COcr_CIOcrResult, 0x9bd235b2, 0x175b, 0x3d6a, 0x92,0xe2, 0x38,0x8c,0x20,0x6e,0x2f,0x63);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                MIDL_INTERFACE("9bd235b2-175b-3d6a-92e2-388c206e2f63")
                IOcrResult : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_Lines(
                        ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Media::Ocr::OcrLine* > **value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_TextAngle(
                        ABI::Windows::Foundation::IReference<DOUBLE > **value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_Text(
                        HSTRING *value) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_COcr_CIOcrResult, 0x9bd235b2, 0x175b, 0x3d6a, 0x92,0xe2, 0x38,0x8c,0x20,0x6e,0x2f,0x63)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_CIOcrResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        TrustLevel *trustLevel);

    /*** IOcrResult methods ***/
    HRESULT (STDMETHODCALLTYPE *get_Lines)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine **value);

    HRESULT (STDMETHODCALLTYPE *get_TextAngle)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        __FIReference_1_DOUBLE **value);

    HRESULT (STDMETHODCALLTYPE *get_Text)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult *This,
        HSTRING *value);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_COcr_CIOcrResultVtbl;

interface __x_ABI_CWindows_CMedia_COcr_CIOcrResult {
    CONST_VTBL __x_ABI_CWindows_CMedia_COcr_CIOcrResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IOcrResult methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Lines(This,value) (This)->lpVtbl->get_Lines(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_TextAngle(This,value) (This)->lpVtbl->get_TextAngle(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Text(This,value) (This)->lpVtbl->get_Text(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_QueryInterface(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrResult_AddRef(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrResult_Release(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetIids(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetRuntimeClassName(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetTrustLevel(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IOcrResult methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Lines(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,__FIVectorView_1_Windows__CMedia__COcr__COcrLine **value) {
    return This->lpVtbl->get_Lines(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_TextAngle(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,__FIReference_1_DOUBLE **value) {
    return This->lpVtbl->get_TextAngle(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Text(__x_ABI_CWindows_CMedia_COcr_CIOcrResult* This,HSTRING *value) {
    return This->lpVtbl->get_Text(This,value);
}
#endif
#ifdef WIDL_using_Windows_Media_Ocr
#define IID_IOcrResult IID___x_ABI_CWindows_CMedia_COcr_CIOcrResult
#define IOcrResultVtbl __x_ABI_CWindows_CMedia_COcr_CIOcrResultVtbl
#define IOcrResult __x_ABI_CWindows_CMedia_COcr_CIOcrResult
#define IOcrResult_QueryInterface __x_ABI_CWindows_CMedia_COcr_CIOcrResult_QueryInterface
#define IOcrResult_AddRef __x_ABI_CWindows_CMedia_COcr_CIOcrResult_AddRef
#define IOcrResult_Release __x_ABI_CWindows_CMedia_COcr_CIOcrResult_Release
#define IOcrResult_GetIids __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetIids
#define IOcrResult_GetRuntimeClassName __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetRuntimeClassName
#define IOcrResult_GetTrustLevel __x_ABI_CWindows_CMedia_COcr_CIOcrResult_GetTrustLevel
#define IOcrResult_get_Lines __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Lines
#define IOcrResult_get_TextAngle __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_TextAngle
#define IOcrResult_get_Text __x_ABI_CWindows_CMedia_COcr_CIOcrResult_get_Text
#endif /* WIDL_using_Windows_Media_Ocr */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_COcr_CIOcrResult_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IOcrEngine interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_COcr_CIOcrEngine, 0x5a14bc41, 0x5b76, 0x3140, 0xb6,0x80, 0x88,0x25,0x56,0x26,0x83,0xac);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                MIDL_INTERFACE("5a14bc41-5b76-3140-b680-8825562683ac")
                IOcrEngine : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE RecognizeAsync(
                        ABI::Windows::Graphics::Imaging::ISoftwareBitmap *bitmap,
                        ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > **result) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_RecognizerLanguage(
                        ABI::Windows::Globalization::ILanguage **value) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine, 0x5a14bc41, 0x5b76, 0x3140, 0xb6,0x80, 0x88,0x25,0x56,0x26,0x83,0xac)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_CIOcrEngineVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        TrustLevel *trustLevel);

    /*** IOcrEngine methods ***/
    HRESULT (STDMETHODCALLTYPE *RecognizeAsync)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        __x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap *bitmap,
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult **result);

    HRESULT (STDMETHODCALLTYPE *get_RecognizerLanguage)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine *This,
        __x_ABI_CWindows_CGlobalization_CILanguage **value);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_COcr_CIOcrEngineVtbl;

interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngine {
    CONST_VTBL __x_ABI_CWindows_CMedia_COcr_CIOcrEngineVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IOcrEngine methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_RecognizeAsync(This,bitmap,result) (This)->lpVtbl->RecognizeAsync(This,bitmap,result)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_get_RecognizerLanguage(This,value) (This)->lpVtbl->get_RecognizerLanguage(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_QueryInterface(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_AddRef(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_Release(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetIids(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetRuntimeClassName(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetTrustLevel(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IOcrEngine methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_RecognizeAsync(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,__x_ABI_CWindows_CGraphics_CImaging_CISoftwareBitmap *bitmap,__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult **result) {
    return This->lpVtbl->RecognizeAsync(This,bitmap,result);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_get_RecognizerLanguage(__x_ABI_CWindows_CMedia_COcr_CIOcrEngine* This,__x_ABI_CWindows_CGlobalization_CILanguage **value) {
    return This->lpVtbl->get_RecognizerLanguage(This,value);
}
#endif
#ifdef WIDL_using_Windows_Media_Ocr
#define IID_IOcrEngine IID___x_ABI_CWindows_CMedia_COcr_CIOcrEngine
#define IOcrEngineVtbl __x_ABI_CWindows_CMedia_COcr_CIOcrEngineVtbl
#define IOcrEngine __x_ABI_CWindows_CMedia_COcr_CIOcrEngine
#define IOcrEngine_QueryInterface __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_QueryInterface
#define IOcrEngine_AddRef __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_AddRef
#define IOcrEngine_Release __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_Release
#define IOcrEngine_GetIids __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetIids
#define IOcrEngine_GetRuntimeClassName __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetRuntimeClassName
#define IOcrEngine_GetTrustLevel __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_GetTrustLevel
#define IOcrEngine_RecognizeAsync __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_RecognizeAsync
#define IOcrEngine_get_RecognizerLanguage __x_ABI_CWindows_CMedia_COcr_CIOcrEngine_get_RecognizerLanguage
#endif /* WIDL_using_Windows_Media_Ocr */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_COcr_CIOcrEngine_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IOcrEngineStatics interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics, 0x5bffa85a, 0x3384, 0x3540, 0x99,0x40, 0x69,0x91,0x20,0xd4,0x28,0xa8);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Media {
            namespace Ocr {
                MIDL_INTERFACE("5bffa85a-3384-3540-9940-699120d428a8")
                IOcrEngineStatics : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_MaxImageDimension(
                        UINT32 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_AvailableRecognizerLanguages(
                        ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::Globalization::Language* > **value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE IsLanguageSupported(
                        ABI::Windows::Globalization::ILanguage *language,
                        boolean *result) = 0;

                    virtual HRESULT STDMETHODCALLTYPE TryCreateFromLanguage(
                        ABI::Windows::Globalization::ILanguage *language,
                        ABI::Windows::Media::Ocr::IOcrEngine **result) = 0;

                    virtual HRESULT STDMETHODCALLTYPE TryCreateFromUserProfileLanguages(
                        ABI::Windows::Media::Ocr::IOcrEngine **result) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics, 0x5bffa85a, 0x3384, 0x3540, 0x99,0x40, 0x69,0x91,0x20,0xd4,0x28,0xa8)
#endif
#else
typedef struct __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStaticsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        TrustLevel *trustLevel);

    /*** IOcrEngineStatics methods ***/
    HRESULT (STDMETHODCALLTYPE *get_MaxImageDimension)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        UINT32 *value);

    HRESULT (STDMETHODCALLTYPE *get_AvailableRecognizerLanguages)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        __FIVectorView_1_Windows__CGlobalization__CLanguage **value);

    HRESULT (STDMETHODCALLTYPE *IsLanguageSupported)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        __x_ABI_CWindows_CGlobalization_CILanguage *language,
        boolean *result);

    HRESULT (STDMETHODCALLTYPE *TryCreateFromLanguage)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        __x_ABI_CWindows_CGlobalization_CILanguage *language,
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine **result);

    HRESULT (STDMETHODCALLTYPE *TryCreateFromUserProfileLanguages)(
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics *This,
        __x_ABI_CWindows_CMedia_COcr_CIOcrEngine **result);

    END_INTERFACE
} __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStaticsVtbl;

interface __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics {
    CONST_VTBL __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStaticsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IOcrEngineStatics methods ***/
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_MaxImageDimension(This,value) (This)->lpVtbl->get_MaxImageDimension(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_AvailableRecognizerLanguages(This,value) (This)->lpVtbl->get_AvailableRecognizerLanguages(This,value)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_IsLanguageSupported(This,language,result) (This)->lpVtbl->IsLanguageSupported(This,language,result)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromLanguage(This,language,result) (This)->lpVtbl->TryCreateFromLanguage(This,language,result)
#define __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromUserProfileLanguages(This,result) (This)->lpVtbl->TryCreateFromUserProfileLanguages(This,result)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_QueryInterface(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_AddRef(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_Release(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetIids(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetRuntimeClassName(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetTrustLevel(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IOcrEngineStatics methods ***/
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_MaxImageDimension(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,UINT32 *value) {
    return This->lpVtbl->get_MaxImageDimension(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_AvailableRecognizerLanguages(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,__FIVectorView_1_Windows__CGlobalization__CLanguage **value) {
    return This->lpVtbl->get_AvailableRecognizerLanguages(This,value);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_IsLanguageSupported(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,__x_ABI_CWindows_CGlobalization_CILanguage *language,boolean *result) {
    return This->lpVtbl->IsLanguageSupported(This,language,result);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromLanguage(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,__x_ABI_CWindows_CGlobalization_CILanguage *language,__x_ABI_CWindows_CMedia_COcr_CIOcrEngine **result) {
    return This->lpVtbl->TryCreateFromLanguage(This,language,result);
}
static inline HRESULT __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromUserProfileLanguages(__x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics* This,__x_ABI_CWindows_CMedia_COcr_CIOcrEngine **result) {
    return This->lpVtbl->TryCreateFromUserProfileLanguages(This,result);
}
#endif
#ifdef WIDL_using_Windows_Media_Ocr
#define IID_IOcrEngineStatics IID___x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics
#define IOcrEngineStaticsVtbl __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStaticsVtbl
#define IOcrEngineStatics __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics
#define IOcrEngineStatics_QueryInterface __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_QueryInterface
#define IOcrEngineStatics_AddRef __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_AddRef
#define IOcrEngineStatics_Release __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_Release
#define IOcrEngineStatics_GetIids __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetIids
#define IOcrEngineStatics_GetRuntimeClassName __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetRuntimeClassName
#define IOcrEngineStatics_GetTrustLevel __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_GetTrustLevel
#define IOcrEngineStatics_get_MaxImageDimension __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_MaxImageDimension
#define IOcrEngineStatics_get_AvailableRecognizerLanguages __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_get_AvailableRecognizerLanguages
#define IOcrEngineStatics_IsLanguageSupported __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_IsLanguageSupported
#define IOcrEngineStatics_TryCreateFromLanguage __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromLanguage
#define IOcrEngineStatics_TryCreateFromUserProfileLanguages __x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_TryCreateFromUserProfileLanguages
#endif /* WIDL_using_Windows_Media_Ocr */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CMedia_COcr_CIOcrEngineStatics_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* > interface
 */
#ifndef ____FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult, 0x989c1371, 0x444a, 0x5e7e, 0xb1,0x97, 0x9e,0xaa,0xf9,0xd2,0x82,0x9a);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("989c1371-444a-5e7e-b197-9eaaf9d2829a")
            IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* > : IAsyncOperationCompletedHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::Media::Ocr::OcrResult*, ABI::Windows::Media::Ocr::IOcrResult* > >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult, 0x989c1371, 0x444a, 0x5e7e, 0xb1,0x97, 0x9e,0xaa,0xf9,0xd2,0x82,0x9a)
#endif
#else
typedef struct __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *This);

    /*** IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *This,
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *info,
        AsyncStatus status);

    END_INTERFACE
} __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResultVtbl;

interface __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult {
    CONST_VTBL __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
#define __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Invoke(This,info,status) (This)->lpVtbl->Invoke(This,info,status)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_QueryInterface(__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_AddRef(__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Release(__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncOperationCompletedHandler<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Invoke(__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult* This,__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *info,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,info,status);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperationCompletedHandler_OcrResult IID___FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult
#define IAsyncOperationCompletedHandler_OcrResultVtbl __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResultVtbl
#define IAsyncOperationCompletedHandler_OcrResult __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult
#define IAsyncOperationCompletedHandler_OcrResult_QueryInterface __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_QueryInterface
#define IAsyncOperationCompletedHandler_OcrResult_AddRef __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_AddRef
#define IAsyncOperationCompletedHandler_OcrResult_Release __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Release
#define IAsyncOperationCompletedHandler_OcrResult_Invoke __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_Invoke
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > interface
 */
#ifndef ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__
#define ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult, 0xc7d7118e, 0xae36, 0x59c0, 0xac,0x76, 0x7b,0xad,0xee,0x71,0x1c,0x8b);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("c7d7118e-ae36-59c0-ac76-7badee711c8b")
            IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > : IAsyncOperation_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::Media::Ocr::OcrResult*, ABI::Windows::Media::Ocr::IOcrResult* > >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult, 0xc7d7118e, 0xae36, 0x59c0, 0xac,0x76, 0x7b,0xad,0xee,0x71,0x1c,0x8b)
#endif
#else
typedef struct __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        TrustLevel *trustLevel);

    /*** IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        __FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult **handler);

    HRESULT (STDMETHODCALLTYPE *GetResults)(
        __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult *This,
        __x_ABI_CWindows_CMedia_COcr_CIOcrResult **results);

    END_INTERFACE
} __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResultVtbl;

interface __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult {
    CONST_VTBL __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetResults(This,results) (This)->lpVtbl->GetResults(This,results)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_QueryInterface(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_AddRef(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_Release(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetIids(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetRuntimeClassName(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetTrustLevel(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IAsyncOperation<ABI::Windows::Media::Ocr::OcrResult* > methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_put_Completed(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_get_Completed(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,__FIAsyncOperationCompletedHandler_1_Windows__CMedia__COcr__COcrResult **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetResults(__FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult* This,__x_ABI_CWindows_CMedia_COcr_CIOcrResult **results) {
    return This->lpVtbl->GetResults(This,results);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperation_OcrResult IID___FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult
#define IAsyncOperation_OcrResultVtbl __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResultVtbl
#define IAsyncOperation_OcrResult __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult
#define IAsyncOperation_OcrResult_QueryInterface __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_QueryInterface
#define IAsyncOperation_OcrResult_AddRef __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_AddRef
#define IAsyncOperation_OcrResult_Release __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_Release
#define IAsyncOperation_OcrResult_GetIids __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetIids
#define IAsyncOperation_OcrResult_GetRuntimeClassName __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetRuntimeClassName
#define IAsyncOperation_OcrResult_GetTrustLevel __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetTrustLevel
#define IAsyncOperation_OcrResult_put_Completed __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_put_Completed
#define IAsyncOperation_OcrResult_get_Completed __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_get_Completed
#define IAsyncOperation_OcrResult_GetResults __FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_GetResults
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperation_1_Windows__CMedia__COcr__COcrResult_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IVectorView<ABI::Windows::Media::Ocr::OcrLine* > interface
 */
#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_INTERFACE_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIVectorView_1_Windows__CMedia__COcr__COcrLine, 0x60c76eac, 0x8875, 0x5ddb, 0xa1,0x9b, 0x65,0xa3,0x93,0x62,0x79,0xea);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            namespace Collections {
                template<>
                MIDL_INTERFACE("60c76eac-8875-5ddb-a19b-65a3936279ea")
                IVectorView<ABI::Windows::Media::Ocr::OcrLine* > : IVectorView_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::Media::Ocr::OcrLine*, ABI::Windows::Media::Ocr::IOcrLine* > >
                {
                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIVectorView_1_Windows__CMedia__COcr__COcrLine, 0x60c76eac, 0x8875, 0x5ddb, 0xa1,0x9b, 0x65,0xa3,0x93,0x62,0x79,0xea)
#endif
#else
typedef struct __FIVectorView_1_Windows__CMedia__COcr__COcrLineVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        TrustLevel *trustLevel);

    /*** IVectorView<ABI::Windows::Media::Ocr::OcrLine* > methods ***/
    HRESULT (STDMETHODCALLTYPE *GetAt)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        UINT32 index,
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine **value);

    HRESULT (STDMETHODCALLTYPE *get_Size)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        UINT32 *value);

    HRESULT (STDMETHODCALLTYPE *IndexOf)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine *element,
        UINT32 *index,
        BOOLEAN *value);

    HRESULT (STDMETHODCALLTYPE *GetMany)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrLine *This,
        UINT32 start_index,
        UINT32 items_size,
        __x_ABI_CWindows_CMedia_COcr_CIOcrLine **items,
        UINT32 *value);

    END_INTERFACE
} __FIVectorView_1_Windows__CMedia__COcr__COcrLineVtbl;

interface __FIVectorView_1_Windows__CMedia__COcr__COcrLine {
    CONST_VTBL __FIVectorView_1_Windows__CMedia__COcr__COcrLineVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IVectorView<ABI::Windows::Media::Ocr::OcrLine* > methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetAt(This,index,value) (This)->lpVtbl->GetAt(This,index,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_get_Size(This,value) (This)->lpVtbl->get_Size(This,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_IndexOf(This,element,index,value) (This)->lpVtbl->IndexOf(This,element,index,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetMany(This,start_index,items_size,items,value) (This)->lpVtbl->GetMany(This,start_index,items_size,items,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_QueryInterface(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIVectorView_1_Windows__CMedia__COcr__COcrLine_AddRef(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIVectorView_1_Windows__CMedia__COcr__COcrLine_Release(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetIids(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetRuntimeClassName(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetTrustLevel(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IVectorView<ABI::Windows::Media::Ocr::OcrLine* > methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetAt(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,UINT32 index,__x_ABI_CWindows_CMedia_COcr_CIOcrLine **value) {
    return This->lpVtbl->GetAt(This,index,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_get_Size(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,UINT32 *value) {
    return This->lpVtbl->get_Size(This,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_IndexOf(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,__x_ABI_CWindows_CMedia_COcr_CIOcrLine *element,UINT32 *index,BOOLEAN *value) {
    return This->lpVtbl->IndexOf(This,element,index,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetMany(__FIVectorView_1_Windows__CMedia__COcr__COcrLine* This,UINT32 start_index,UINT32 items_size,__x_ABI_CWindows_CMedia_COcr_CIOcrLine **items,UINT32 *value) {
    return This->lpVtbl->GetMany(This,start_index,items_size,items,value);
}
#endif
#ifdef WIDL_using_Windows_Foundation_Collections
#define IID_IVectorView_OcrLine IID___FIVectorView_1_Windows__CMedia__COcr__COcrLine
#define IVectorView_OcrLineVtbl __FIVectorView_1_Windows__CMedia__COcr__COcrLineVtbl
#define IVectorView_OcrLine __FIVectorView_1_Windows__CMedia__COcr__COcrLine
#define IVectorView_OcrLine_QueryInterface __FIVectorView_1_Windows__CMedia__COcr__COcrLine_QueryInterface
#define IVectorView_OcrLine_AddRef __FIVectorView_1_Windows__CMedia__COcr__COcrLine_AddRef
#define IVectorView_OcrLine_Release __FIVectorView_1_Windows__CMedia__COcr__COcrLine_Release
#define IVectorView_OcrLine_GetIids __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetIids
#define IVectorView_OcrLine_GetRuntimeClassName __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetRuntimeClassName
#define IVectorView_OcrLine_GetTrustLevel __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetTrustLevel
#define IVectorView_OcrLine_GetAt __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetAt
#define IVectorView_OcrLine_get_Size __FIVectorView_1_Windows__CMedia__COcr__COcrLine_get_Size
#define IVectorView_OcrLine_IndexOf __FIVectorView_1_Windows__CMedia__COcr__COcrLine_IndexOf
#define IVectorView_OcrLine_GetMany __FIVectorView_1_Windows__CMedia__COcr__COcrLine_GetMany
#endif /* WIDL_using_Windows_Foundation_Collections */
#endif

#endif

#endif  /* ____FIVectorView_1_Windows__CMedia__COcr__COcrLine_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IVectorView<ABI::Windows::Media::Ocr::OcrWord* > interface
 */
#ifndef ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_INTERFACE_DEFINED__
#define ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIVectorView_1_Windows__CMedia__COcr__COcrWord, 0x805a60c7, 0xdf4f, 0x527c, 0x86,0xb2, 0xe2,0x9e,0x43,0x9a,0x83,0xd2);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            namespace Collections {
                template<>
                MIDL_INTERFACE("805a60c7-df4f-527c-86b2-e29e439a83d2")
                IVectorView<ABI::Windows::Media::Ocr::OcrWord* > : IVectorView_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::Media::Ocr::OcrWord*, ABI::Windows::Media::Ocr::IOcrWord* > >
                {
                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIVectorView_1_Windows__CMedia__COcr__COcrWord, 0x805a60c7, 0xdf4f, 0x527c, 0x86,0xb2, 0xe2,0x9e,0x43,0x9a,0x83,0xd2)
#endif
#else
typedef struct __FIVectorView_1_Windows__CMedia__COcr__COcrWordVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        TrustLevel *trustLevel);

    /*** IVectorView<ABI::Windows::Media::Ocr::OcrWord* > methods ***/
    HRESULT (STDMETHODCALLTYPE *GetAt)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        UINT32 index,
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord **value);

    HRESULT (STDMETHODCALLTYPE *get_Size)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        UINT32 *value);

    HRESULT (STDMETHODCALLTYPE *IndexOf)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord *element,
        UINT32 *index,
        BOOLEAN *value);

    HRESULT (STDMETHODCALLTYPE *GetMany)(
        __FIVectorView_1_Windows__CMedia__COcr__COcrWord *This,
        UINT32 start_index,
        UINT32 items_size,
        __x_ABI_CWindows_CMedia_COcr_CIOcrWord **items,
        UINT32 *value);

    END_INTERFACE
} __FIVectorView_1_Windows__CMedia__COcr__COcrWordVtbl;

interface __FIVectorView_1_Windows__CMedia__COcr__COcrWord {
    CONST_VTBL __FIVectorView_1_Windows__CMedia__COcr__COcrWordVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IVectorView<ABI::Windows::Media::Ocr::OcrWord* > methods ***/
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetAt(This,index,value) (This)->lpVtbl->GetAt(This,index,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_get_Size(This,value) (This)->lpVtbl->get_Size(This,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_IndexOf(This,element,index,value) (This)->lpVtbl->IndexOf(This,element,index,value)
#define __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetMany(This,start_index,items_size,items,value) (This)->lpVtbl->GetMany(This,start_index,items_size,items,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_QueryInterface(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIVectorView_1_Windows__CMedia__COcr__COcrWord_AddRef(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIVectorView_1_Windows__CMedia__COcr__COcrWord_Release(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetIids(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetRuntimeClassName(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetTrustLevel(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IVectorView<ABI::Windows::Media::Ocr::OcrWord* > methods ***/
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetAt(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,UINT32 index,__x_ABI_CWindows_CMedia_COcr_CIOcrWord **value) {
    return This->lpVtbl->GetAt(This,index,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_get_Size(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,UINT32 *value) {
    return This->lpVtbl->get_Size(This,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_IndexOf(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,__x_ABI_CWindows_CMedia_COcr_CIOcrWord *element,UINT32 *index,BOOLEAN *value) {
    return This->lpVtbl->IndexOf(This,element,index,value);
}
static inline HRESULT __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetMany(__FIVectorView_1_Windows__CMedia__COcr__COcrWord* This,UINT32 start_index,UINT32 items_size,__x_ABI_CWindows_CMedia_COcr_CIOcrWord **items,UINT32 *value) {
    return This->lpVtbl->GetMany(This,start_index,items_size,items,value);
}
#endif
#ifdef WIDL_using_Windows_Foundation_Collections
#define IID_IVectorView_OcrWord IID___FIVectorView_1_Windows__CMedia__COcr__COcrWord
#define IVectorView_OcrWordVtbl __FIVectorView_1_Windows__CMedia__COcr__COcrWordVtbl
#define IVectorView_OcrWord __FIVectorView_1_Windows__CMedia__COcr__COcrWord
#define IVectorView_OcrWord_QueryInterface __FIVectorView_1_Windows__CMedia__COcr__COcrWord_QueryInterface
#define IVectorView_OcrWord_AddRef __FIVectorView_1_Windows__CMedia__COcr__COcrWord_AddRef
#define IVectorView_OcrWord_Release __FIVectorView_1_Windows__CMedia__COcr__COcrWord_Release
#define IVectorView_OcrWord_GetIids __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetIids
#define IVectorView_OcrWord_GetRuntimeClassName __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetRuntimeClassName
#define IVectorView_OcrWord_GetTrustLevel __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetTrustLevel
#define IVectorView_OcrWord_GetAt __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetAt
#define IVectorView_OcrWord_get_Size __FIVectorView_1_Windows__CMedia__COcr__COcrWord_get_Size
#define IVectorView_OcrWord_IndexOf __FIVectorView_1_Windows__CMedia__COcr__COcrWord_IndexOf
#define IVectorView_OcrWord_GetMany __FIVectorView_1_Windows__CMedia__COcr__COcrWord_GetMany
#endif /* WIDL_using_Windows_Foundation_Collections */
#endif

#endif

#endif  /* ____FIVectorView_1_Windows__CMedia__COcr__COcrWord_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HSTRING_UserSize     (ULONG *, ULONG, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserMarshal  (ULONG *, unsigned char *, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserUnmarshal(ULONG *, unsigned char *, HSTRING *);
void            __RPC_USER HSTRING_UserFree     (ULONG *, HSTRING *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __windows_media_ocr_h__ */
