/*** Autogenerated by WIDL 10.9 from windows.ui.xaml.controls.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_ui_xaml_controls_h__
#define __windows_ui_xaml_controls_h__

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CUI_CCore_CCoreIndependentInputSource_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CCoreIndependentInputSource_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Core {
                class CoreIndependentInputSource;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CUI_CCore_CCoreIndependentInputSource __x_ABI_CWindows_CUI_CCore_CCoreIndependentInputSource;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CUI_CCore_CCoreIndependentInputSource_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CUI_CXaml_CControls_CSwapChainPanel_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CXaml_CControls_CSwapChainPanel_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Xaml {
                namespace Controls {
                    class SwapChainPanel;
                }
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CUI_CXaml_CControls_CSwapChainPanel __x_ABI_CWindows_CUI_CXaml_CControls_CSwapChainPanel;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CUI_CXaml_CControls_CSwapChainPanel_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel;
#ifdef __cplusplus
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel ABI::Windows::UI::Xaml::Controls::ISwapChainPanel
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Xaml {
                namespace Controls {
                    interface ISwapChainPanel;
                }
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_FWD_DEFINED__
#define ____FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_FWD_DEFINED__
typedef interface __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable;
#ifdef __cplusplus
#define __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable ABI::Windows::Foundation::ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* >
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>
#include <windows.ui.core.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __cplusplus
typedef enum __x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes __x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes;
#endif /* __cplusplus */

#ifndef ____x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase __x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase;
#ifdef __cplusplus
#define __x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase ABI::Windows::UI::Core::ICoreInputSourceBase
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Core {
                interface ICoreInputSourceBase;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifdef __cplusplus
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Core {
                enum CoreInputDeviceTypes {
                    CoreInputDeviceTypes_None = 0x0,
                    CoreInputDeviceTypes_Touch = 0x1,
                    CoreInputDeviceTypes_Pen = 0x2,
                    CoreInputDeviceTypes_Mouse = 0x4
                };
            }
        }
    }
}
extern "C" {
#else
enum __x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes {
    CoreInputDeviceTypes_None = 0x0,
    CoreInputDeviceTypes_Touch = 0x1,
    CoreInputDeviceTypes_Pen = 0x2,
    CoreInputDeviceTypes_Mouse = 0x4
};
#ifdef WIDL_using_Windows_UI_Core
#define CoreInputDeviceTypes __x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes
#endif /* WIDL_using_Windows_UI_Core */
#endif

#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */
/*
 * Class Windows.UI.Core.CoreIndependentInputSource
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_UI_Core_CoreIndependentInputSource_DEFINED
#define RUNTIMECLASS_Windows_UI_Core_CoreIndependentInputSource_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_UI_Core_CoreIndependentInputSource[] = {'W','i','n','d','o','w','s','.','U','I','.','C','o','r','e','.','C','o','r','e','I','n','d','e','p','e','n','d','e','n','t','I','n','p','u','t','S','o','u','r','c','e',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_UI_Core_CoreIndependentInputSource[] = L"Windows.UI.Core.CoreIndependentInputSource";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_UI_Core_CoreIndependentInputSource[] = {'W','i','n','d','o','w','s','.','U','I','.','C','o','r','e','.','C','o','r','e','I','n','d','e','p','e','n','d','e','n','t','I','n','p','u','t','S','o','u','r','c','e',0};
#endif
#endif /* RUNTIMECLASS_Windows_UI_Core_CoreIndependentInputSource_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

#ifndef ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel;
#ifdef __cplusplus
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel ABI::Windows::UI::Xaml::Controls::ISwapChainPanel
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Xaml {
                namespace Controls {
                    interface ISwapChainPanel;
                }
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
#define ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel;
#ifdef __cplusplus
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel ABI::Windows::UI::Xaml::Controls::ISwapChainPanel
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Xaml {
                namespace Controls {
                    interface ISwapChainPanel;
                }
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/*
 * Class Windows.UI.Xaml.Controls.SwapChainPanel
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_UI_Xaml_Controls_SwapChainPanel_DEFINED
#define RUNTIMECLASS_Windows_UI_Xaml_Controls_SwapChainPanel_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_UI_Xaml_Controls_SwapChainPanel[] = {'W','i','n','d','o','w','s','.','U','I','.','X','a','m','l','.','C','o','n','t','r','o','l','s','.','S','w','a','p','C','h','a','i','n','P','a','n','e','l',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_UI_Xaml_Controls_SwapChainPanel[] = L"Windows.UI.Xaml.Controls.SwapChainPanel";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_UI_Xaml_Controls_SwapChainPanel[] = {'W','i','n','d','o','w','s','.','U','I','.','X','a','m','l','.','C','o','n','t','r','o','l','s','.','S','w','a','p','C','h','a','i','n','P','a','n','e','l',0};
#endif
#endif /* RUNTIMECLASS_Windows_UI_Xaml_Controls_SwapChainPanel_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * ISwapChainPanel interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel, 0xc589644f, 0xeba8, 0x427a, 0xb7,0x5a, 0x9f,0x1f,0x93,0xa1,0x1a,0xe9);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace UI {
            namespace Xaml {
                namespace Controls {
                    MIDL_INTERFACE("c589644f-eba8-427a-b75a-9f1f93a11ae9")
                    ISwapChainPanel : public IInspectable
                    {
                        virtual HRESULT STDMETHODCALLTYPE get_CompositionScaleX(
                            FLOAT *value) = 0;

                        virtual HRESULT STDMETHODCALLTYPE get_CompositionScaleY(
                            FLOAT *value) = 0;

                        virtual HRESULT STDMETHODCALLTYPE add_CompositionScaleChanged(
                            ABI::Windows::Foundation::ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > *handler,
                            EventRegistrationToken *token) = 0;

                        virtual HRESULT STDMETHODCALLTYPE remove_CompositionScaleChanged(
                            EventRegistrationToken token) = 0;

                        virtual HRESULT STDMETHODCALLTYPE CreateCoreIndependentInputSource(
                            ABI::Windows::UI::Core::CoreInputDeviceTypes deviceTypes,
                            ABI::Windows::UI::Core::ICoreInputSourceBase **result) = 0;

                    };
                }
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel, 0xc589644f, 0xeba8, 0x427a, 0xb7,0x5a, 0x9f,0x1f,0x93,0xa1,0x1a,0xe9)
#endif
#else
typedef struct __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanelVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        TrustLevel *trustLevel);

    /*** ISwapChainPanel methods ***/
    HRESULT (STDMETHODCALLTYPE *get_CompositionScaleX)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        FLOAT *value);

    HRESULT (STDMETHODCALLTYPE *get_CompositionScaleY)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        FLOAT *value);

    HRESULT (STDMETHODCALLTYPE *add_CompositionScaleChanged)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *handler,
        EventRegistrationToken *token);

    HRESULT (STDMETHODCALLTYPE *remove_CompositionScaleChanged)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        EventRegistrationToken token);

    HRESULT (STDMETHODCALLTYPE *CreateCoreIndependentInputSource)(
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *This,
        __x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes deviceTypes,
        __x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase **result);

    END_INTERFACE
} __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanelVtbl;

interface __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel {
    CONST_VTBL __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanelVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** ISwapChainPanel methods ***/
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleX(This,value) (This)->lpVtbl->get_CompositionScaleX(This,value)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleY(This,value) (This)->lpVtbl->get_CompositionScaleY(This,value)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_add_CompositionScaleChanged(This,handler,token) (This)->lpVtbl->add_CompositionScaleChanged(This,handler,token)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_remove_CompositionScaleChanged(This,token) (This)->lpVtbl->remove_CompositionScaleChanged(This,token)
#define __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_CreateCoreIndependentInputSource(This,deviceTypes,result) (This)->lpVtbl->CreateCoreIndependentInputSource(This,deviceTypes,result)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_QueryInterface(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_AddRef(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_Release(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetIids(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetRuntimeClassName(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetTrustLevel(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** ISwapChainPanel methods ***/
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleX(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,FLOAT *value) {
    return This->lpVtbl->get_CompositionScaleX(This,value);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleY(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,FLOAT *value) {
    return This->lpVtbl->get_CompositionScaleY(This,value);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_add_CompositionScaleChanged(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *handler,EventRegistrationToken *token) {
    return This->lpVtbl->add_CompositionScaleChanged(This,handler,token);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_remove_CompositionScaleChanged(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,EventRegistrationToken token) {
    return This->lpVtbl->remove_CompositionScaleChanged(This,token);
}
static inline HRESULT __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_CreateCoreIndependentInputSource(__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel* This,__x_ABI_CWindows_CUI_CCore_CCoreInputDeviceTypes deviceTypes,__x_ABI_CWindows_CUI_CCore_CICoreInputSourceBase **result) {
    return This->lpVtbl->CreateCoreIndependentInputSource(This,deviceTypes,result);
}
#endif
#ifdef WIDL_using_Windows_UI_Xaml_Controls
#define IID_ISwapChainPanel IID___x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel
#define ISwapChainPanelVtbl __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanelVtbl
#define ISwapChainPanel __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel
#define ISwapChainPanel_QueryInterface __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_QueryInterface
#define ISwapChainPanel_AddRef __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_AddRef
#define ISwapChainPanel_Release __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_Release
#define ISwapChainPanel_GetIids __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetIids
#define ISwapChainPanel_GetRuntimeClassName __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetRuntimeClassName
#define ISwapChainPanel_GetTrustLevel __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_GetTrustLevel
#define ISwapChainPanel_get_CompositionScaleX __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleX
#define ISwapChainPanel_get_CompositionScaleY __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_get_CompositionScaleY
#define ISwapChainPanel_add_CompositionScaleChanged __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_add_CompositionScaleChanged
#define ISwapChainPanel_remove_CompositionScaleChanged __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_remove_CompositionScaleChanged
#define ISwapChainPanel_CreateCoreIndependentInputSource __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_CreateCoreIndependentInputSource
#endif /* WIDL_using_Windows_UI_Xaml_Controls */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > interface
 */
#ifndef ____FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_INTERFACE_DEFINED__
#define ____FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_INTERFACE_DEFINED__

DEFINE_GUID(IID___FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable, 0xa8bbf146, 0xb687, 0x5c03, 0x9a,0x42, 0x2a,0xe2,0xd5,0x5b,0xfb,0xb4);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("a8bbf146-b687-5c03-9a42-2ae2d55bfbb4")
            ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > : ITypedEventHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*, ABI::Windows::UI::Xaml::Controls::ISwapChainPanel* >, IInspectable* >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable, 0xa8bbf146, 0xb687, 0x5c03, 0x9a,0x42, 0x2a,0xe2,0xd5,0x5b,0xfb,0xb4)
#endif
#else
typedef struct __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectableVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *This);

    /*** ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable *This,
        __x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *sender,
        IInspectable *args);

    END_INTERFACE
} __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectableVtbl;

interface __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable {
    CONST_VTBL __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectableVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Release(This) (This)->lpVtbl->Release(This)
/*** ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > methods ***/
#define __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Invoke(This,sender,args) (This)->lpVtbl->Invoke(This,sender,args)
#else
/*** IUnknown methods ***/
static inline HRESULT __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_QueryInterface(__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_AddRef(__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Release(__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable* This) {
    return This->lpVtbl->Release(This);
}
/*** ITypedEventHandler<ABI::Windows::UI::Xaml::Controls::SwapChainPanel*,IInspectable* > methods ***/
static inline HRESULT __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Invoke(__FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable* This,__x_ABI_CWindows_CUI_CXaml_CControls_CISwapChainPanel *sender,IInspectable *args) {
    return This->lpVtbl->Invoke(This,sender,args);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_ITypedEventHandler_SwapChainPanel_IInspectable IID___FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable
#define ITypedEventHandler_SwapChainPanel_IInspectableVtbl __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectableVtbl
#define ITypedEventHandler_SwapChainPanel_IInspectable __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable
#define ITypedEventHandler_SwapChainPanel_IInspectable_QueryInterface __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_QueryInterface
#define ITypedEventHandler_SwapChainPanel_IInspectable_AddRef __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_AddRef
#define ITypedEventHandler_SwapChainPanel_IInspectable_Release __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Release
#define ITypedEventHandler_SwapChainPanel_IInspectable_Invoke __FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_Invoke
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FITypedEventHandler_2_Windows__CUI__CXaml__CControls__CSwapChainPanel_IInspectable_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
namespace ABI { namespace Windows { namespace UI { namespace Core { DEFINE_ENUM_FLAG_OPERATORS(CoreInputDeviceTypes) }}}}
#endif

#endif /* __windows_ui_xaml_controls_h__ */
