/*** Autogenerated by WIDL 10.9 from windows.storage.streams_ext.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_storage_streams_ext_h__
#define __windows_storage_streams_ext_h__

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReader __x_ABI_CWindows_CStorage_CStreams_CIDataReader;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader ABI::Windows::Storage::Streams::IDataReader
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReader;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory ABI::Windows::Storage::Streams::IDataReaderFactory
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReaderFactory;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics ABI::Windows::Storage::Streams::IDataReaderStatics
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReaderStatics;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CDataReader_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CDataReader_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                class DataReader;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CStorage_CStreams_CDataReader __x_ABI_CWindows_CStorage_CStreams_CDataReader;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CStorage_CStreams_CDataReader_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CDataReaderLoadOperation_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CDataReaderLoadOperation_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                class DataReaderLoadOperation;
            }
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CStorage_CStreams_CDataReaderLoadOperation __x_ABI_CWindows_CStorage_CStreams_CDataReaderLoadOperation;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CStorage_CStreams_CDataReaderLoadOperation_FWD_DEFINED__ */

/* Headers for imported files */

#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>
#include <windows.storage.streams.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReader __x_ABI_CWindows_CStorage_CStreams_CIDataReader;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader ABI::Windows::Storage::Streams::IDataReader
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReader;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReader __x_ABI_CWindows_CStorage_CStreams_CIDataReader;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader ABI::Windows::Storage::Streams::IDataReader
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReader;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory ABI::Windows::Storage::Streams::IDataReaderFactory
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReaderFactory;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics;
#ifdef __cplusplus
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics ABI::Windows::Storage::Streams::IDataReaderStatics
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                interface IDataReaderStatics;
            }
        }
    }
}
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * IDataReader interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CStorage_CStreams_CIDataReader, 0xe2b50029, 0xb4c1, 0x4314, 0xa4,0xb8, 0xfb,0x81,0x3a,0x2f,0x27,0x5e);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                MIDL_INTERFACE("e2b50029-b4c1-4314-a4b8-fb813a2f275e")
                IDataReader : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE get_UnconsumedBufferLength(
                        UINT32 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_UnicodeEncoding(
                        ABI::Windows::Storage::Streams::UnicodeEncoding *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE put_UnicodeEncoding(
                        ABI::Windows::Storage::Streams::UnicodeEncoding value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_ByteOrder(
                        ABI::Windows::Storage::Streams::ByteOrder *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE put_ByteOrder(
                        ABI::Windows::Storage::Streams::ByteOrder value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE get_InputStreamOptions(
                        ABI::Windows::Storage::Streams::InputStreamOptions *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE put_InputStreamOptions(
                        ABI::Windows::Storage::Streams::InputStreamOptions value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadByte(
                        BYTE *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadBytes(
                        UINT32 __valueSize,
                        BYTE *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadBuffer(
                        UINT32 length,
                        ABI::Windows::Storage::Streams::IBuffer **buffer) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadBoolean(
                        boolean *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadGuid(
                        GUID *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadInt16(
                        INT16 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadInt32(
                        INT32 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadInt64(
                        INT64 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadUInt16(
                        UINT16 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadUInt32(
                        UINT32 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadUInt64(
                        UINT64 *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadSingle(
                        FLOAT *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadDouble(
                        DOUBLE *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadString(
                        UINT32 codeUnitCount,
                        HSTRING *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadDateTime(
                        ABI::Windows::Foundation::DateTime *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE ReadTimeSpan(
                        ABI::Windows::Foundation::TimeSpan *value) = 0;

                    virtual HRESULT STDMETHODCALLTYPE LoadAsync(
                        UINT32 count,
                        ABI::Windows::Foundation::IAsyncOperation<UINT32 > **operation) = 0;

                    virtual HRESULT STDMETHODCALLTYPE DetachBuffer(
                        ABI::Windows::Storage::Streams::IBuffer **buffer) = 0;

                    virtual HRESULT STDMETHODCALLTYPE DetachStream(
                        ABI::Windows::Storage::Streams::IInputStream **stream) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CStorage_CStreams_CIDataReader, 0xe2b50029, 0xb4c1, 0x4314, 0xa4,0xb8, 0xfb,0x81,0x3a,0x2f,0x27,0x5e)
#endif
#else
typedef struct __x_ABI_CWindows_CStorage_CStreams_CIDataReaderVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        TrustLevel *trustLevel);

    /*** IDataReader methods ***/
    HRESULT (STDMETHODCALLTYPE *get_UnconsumedBufferLength)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 *value);

    HRESULT (STDMETHODCALLTYPE *get_UnicodeEncoding)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CUnicodeEncoding *value);

    HRESULT (STDMETHODCALLTYPE *put_UnicodeEncoding)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CUnicodeEncoding value);

    HRESULT (STDMETHODCALLTYPE *get_ByteOrder)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CByteOrder *value);

    HRESULT (STDMETHODCALLTYPE *put_ByteOrder)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CByteOrder value);

    HRESULT (STDMETHODCALLTYPE *get_InputStreamOptions)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CInputStreamOptions *value);

    HRESULT (STDMETHODCALLTYPE *put_InputStreamOptions)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CInputStreamOptions value);

    HRESULT (STDMETHODCALLTYPE *ReadByte)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        BYTE *value);

    HRESULT (STDMETHODCALLTYPE *ReadBytes)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 __valueSize,
        BYTE *value);

    HRESULT (STDMETHODCALLTYPE *ReadBuffer)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 length,
        __x_ABI_CWindows_CStorage_CStreams_CIBuffer **buffer);

    HRESULT (STDMETHODCALLTYPE *ReadBoolean)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        boolean *value);

    HRESULT (STDMETHODCALLTYPE *ReadGuid)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        GUID *value);

    HRESULT (STDMETHODCALLTYPE *ReadInt16)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        INT16 *value);

    HRESULT (STDMETHODCALLTYPE *ReadInt32)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        INT32 *value);

    HRESULT (STDMETHODCALLTYPE *ReadInt64)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        INT64 *value);

    HRESULT (STDMETHODCALLTYPE *ReadUInt16)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT16 *value);

    HRESULT (STDMETHODCALLTYPE *ReadUInt32)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 *value);

    HRESULT (STDMETHODCALLTYPE *ReadUInt64)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT64 *value);

    HRESULT (STDMETHODCALLTYPE *ReadSingle)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        FLOAT *value);

    HRESULT (STDMETHODCALLTYPE *ReadDouble)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        DOUBLE *value);

    HRESULT (STDMETHODCALLTYPE *ReadString)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 codeUnitCount,
        HSTRING *value);

    HRESULT (STDMETHODCALLTYPE *ReadDateTime)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CFoundation_CDateTime *value);

    HRESULT (STDMETHODCALLTYPE *ReadTimeSpan)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CFoundation_CTimeSpan *value);

    HRESULT (STDMETHODCALLTYPE *LoadAsync)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        UINT32 count,
        __FIAsyncOperation_1_UINT32 **operation);

    HRESULT (STDMETHODCALLTYPE *DetachBuffer)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CIBuffer **buffer);

    HRESULT (STDMETHODCALLTYPE *DetachStream)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader *This,
        __x_ABI_CWindows_CStorage_CStreams_CIInputStream **stream);

    END_INTERFACE
} __x_ABI_CWindows_CStorage_CStreams_CIDataReaderVtbl;

interface __x_ABI_CWindows_CStorage_CStreams_CIDataReader {
    CONST_VTBL __x_ABI_CWindows_CStorage_CStreams_CIDataReaderVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IDataReader methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnconsumedBufferLength(This,value) (This)->lpVtbl->get_UnconsumedBufferLength(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnicodeEncoding(This,value) (This)->lpVtbl->get_UnicodeEncoding(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_UnicodeEncoding(This,value) (This)->lpVtbl->put_UnicodeEncoding(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_ByteOrder(This,value) (This)->lpVtbl->get_ByteOrder(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_ByteOrder(This,value) (This)->lpVtbl->put_ByteOrder(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_InputStreamOptions(This,value) (This)->lpVtbl->get_InputStreamOptions(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_InputStreamOptions(This,value) (This)->lpVtbl->put_InputStreamOptions(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadByte(This,value) (This)->lpVtbl->ReadByte(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBytes(This,__valueSize,value) (This)->lpVtbl->ReadBytes(This,__valueSize,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBuffer(This,length,buffer) (This)->lpVtbl->ReadBuffer(This,length,buffer)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBoolean(This,value) (This)->lpVtbl->ReadBoolean(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadGuid(This,value) (This)->lpVtbl->ReadGuid(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt16(This,value) (This)->lpVtbl->ReadInt16(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt32(This,value) (This)->lpVtbl->ReadInt32(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt64(This,value) (This)->lpVtbl->ReadInt64(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt16(This,value) (This)->lpVtbl->ReadUInt16(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt32(This,value) (This)->lpVtbl->ReadUInt32(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt64(This,value) (This)->lpVtbl->ReadUInt64(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadSingle(This,value) (This)->lpVtbl->ReadSingle(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDouble(This,value) (This)->lpVtbl->ReadDouble(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadString(This,codeUnitCount,value) (This)->lpVtbl->ReadString(This,codeUnitCount,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDateTime(This,value) (This)->lpVtbl->ReadDateTime(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadTimeSpan(This,value) (This)->lpVtbl->ReadTimeSpan(This,value)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_LoadAsync(This,count,operation) (This)->lpVtbl->LoadAsync(This,count,operation)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachBuffer(This,buffer) (This)->lpVtbl->DetachBuffer(This,buffer)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachStream(This,stream) (This)->lpVtbl->DetachStream(This,stream)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_QueryInterface(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReader_AddRef(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReader_Release(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetIids(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetRuntimeClassName(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetTrustLevel(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IDataReader methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnconsumedBufferLength(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 *value) {
    return This->lpVtbl->get_UnconsumedBufferLength(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnicodeEncoding(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CUnicodeEncoding *value) {
    return This->lpVtbl->get_UnicodeEncoding(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_UnicodeEncoding(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CUnicodeEncoding value) {
    return This->lpVtbl->put_UnicodeEncoding(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_ByteOrder(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CByteOrder *value) {
    return This->lpVtbl->get_ByteOrder(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_ByteOrder(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CByteOrder value) {
    return This->lpVtbl->put_ByteOrder(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_InputStreamOptions(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CInputStreamOptions *value) {
    return This->lpVtbl->get_InputStreamOptions(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_InputStreamOptions(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CInputStreamOptions value) {
    return This->lpVtbl->put_InputStreamOptions(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadByte(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,BYTE *value) {
    return This->lpVtbl->ReadByte(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBytes(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 __valueSize,BYTE *value) {
    return This->lpVtbl->ReadBytes(This,__valueSize,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBuffer(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 length,__x_ABI_CWindows_CStorage_CStreams_CIBuffer **buffer) {
    return This->lpVtbl->ReadBuffer(This,length,buffer);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBoolean(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,boolean *value) {
    return This->lpVtbl->ReadBoolean(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadGuid(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,GUID *value) {
    return This->lpVtbl->ReadGuid(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt16(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,INT16 *value) {
    return This->lpVtbl->ReadInt16(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt32(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,INT32 *value) {
    return This->lpVtbl->ReadInt32(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt64(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,INT64 *value) {
    return This->lpVtbl->ReadInt64(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt16(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT16 *value) {
    return This->lpVtbl->ReadUInt16(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt32(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 *value) {
    return This->lpVtbl->ReadUInt32(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt64(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT64 *value) {
    return This->lpVtbl->ReadUInt64(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadSingle(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,FLOAT *value) {
    return This->lpVtbl->ReadSingle(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDouble(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,DOUBLE *value) {
    return This->lpVtbl->ReadDouble(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadString(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 codeUnitCount,HSTRING *value) {
    return This->lpVtbl->ReadString(This,codeUnitCount,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDateTime(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CFoundation_CDateTime *value) {
    return This->lpVtbl->ReadDateTime(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadTimeSpan(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CFoundation_CTimeSpan *value) {
    return This->lpVtbl->ReadTimeSpan(This,value);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_LoadAsync(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,UINT32 count,__FIAsyncOperation_1_UINT32 **operation) {
    return This->lpVtbl->LoadAsync(This,count,operation);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachBuffer(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CIBuffer **buffer) {
    return This->lpVtbl->DetachBuffer(This,buffer);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachStream(__x_ABI_CWindows_CStorage_CStreams_CIDataReader* This,__x_ABI_CWindows_CStorage_CStreams_CIInputStream **stream) {
    return This->lpVtbl->DetachStream(This,stream);
}
#endif
#ifdef WIDL_using_Windows_Storage_Streams
#define IID_IDataReader IID___x_ABI_CWindows_CStorage_CStreams_CIDataReader
#define IDataReaderVtbl __x_ABI_CWindows_CStorage_CStreams_CIDataReaderVtbl
#define IDataReader __x_ABI_CWindows_CStorage_CStreams_CIDataReader
#define IDataReader_QueryInterface __x_ABI_CWindows_CStorage_CStreams_CIDataReader_QueryInterface
#define IDataReader_AddRef __x_ABI_CWindows_CStorage_CStreams_CIDataReader_AddRef
#define IDataReader_Release __x_ABI_CWindows_CStorage_CStreams_CIDataReader_Release
#define IDataReader_GetIids __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetIids
#define IDataReader_GetRuntimeClassName __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetRuntimeClassName
#define IDataReader_GetTrustLevel __x_ABI_CWindows_CStorage_CStreams_CIDataReader_GetTrustLevel
#define IDataReader_get_UnconsumedBufferLength __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnconsumedBufferLength
#define IDataReader_get_UnicodeEncoding __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_UnicodeEncoding
#define IDataReader_put_UnicodeEncoding __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_UnicodeEncoding
#define IDataReader_get_ByteOrder __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_ByteOrder
#define IDataReader_put_ByteOrder __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_ByteOrder
#define IDataReader_get_InputStreamOptions __x_ABI_CWindows_CStorage_CStreams_CIDataReader_get_InputStreamOptions
#define IDataReader_put_InputStreamOptions __x_ABI_CWindows_CStorage_CStreams_CIDataReader_put_InputStreamOptions
#define IDataReader_ReadByte __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadByte
#define IDataReader_ReadBytes __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBytes
#define IDataReader_ReadBuffer __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBuffer
#define IDataReader_ReadBoolean __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadBoolean
#define IDataReader_ReadGuid __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadGuid
#define IDataReader_ReadInt16 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt16
#define IDataReader_ReadInt32 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt32
#define IDataReader_ReadInt64 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadInt64
#define IDataReader_ReadUInt16 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt16
#define IDataReader_ReadUInt32 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt32
#define IDataReader_ReadUInt64 __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadUInt64
#define IDataReader_ReadSingle __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadSingle
#define IDataReader_ReadDouble __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDouble
#define IDataReader_ReadString __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadString
#define IDataReader_ReadDateTime __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadDateTime
#define IDataReader_ReadTimeSpan __x_ABI_CWindows_CStorage_CStreams_CIDataReader_ReadTimeSpan
#define IDataReader_LoadAsync __x_ABI_CWindows_CStorage_CStreams_CIDataReader_LoadAsync
#define IDataReader_DetachBuffer __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachBuffer
#define IDataReader_DetachStream __x_ABI_CWindows_CStorage_CStreams_CIDataReader_DetachStream
#endif /* WIDL_using_Windows_Storage_Streams */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CStorage_CStreams_CIDataReader_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IDataReaderFactory interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory, 0xd7527847, 0x57da, 0x4e15, 0x91,0x4c, 0x06,0x80,0x66,0x99,0xa0,0x98);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                MIDL_INTERFACE("d7527847-57da-4e15-914c-06806699a098")
                IDataReaderFactory : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE CreateDataReader(
                        ABI::Windows::Storage::Streams::IInputStream *inputStream,
                        ABI::Windows::Storage::Streams::IDataReader **dataReader) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory, 0xd7527847, 0x57da, 0x4e15, 0x91,0x4c, 0x06,0x80,0x66,0x99,0xa0,0x98)
#endif
#else
typedef struct __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactoryVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This,
        TrustLevel *trustLevel);

    /*** IDataReaderFactory methods ***/
    HRESULT (STDMETHODCALLTYPE *CreateDataReader)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory *This,
        __x_ABI_CWindows_CStorage_CStreams_CIInputStream *inputStream,
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader **dataReader);

    END_INTERFACE
} __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactoryVtbl;

interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory {
    CONST_VTBL __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactoryVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IDataReaderFactory methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_CreateDataReader(This,inputStream,dataReader) (This)->lpVtbl->CreateDataReader(This,inputStream,dataReader)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_QueryInterface(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_AddRef(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_Release(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetIids(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetRuntimeClassName(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetTrustLevel(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IDataReaderFactory methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_CreateDataReader(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory* This,__x_ABI_CWindows_CStorage_CStreams_CIInputStream *inputStream,__x_ABI_CWindows_CStorage_CStreams_CIDataReader **dataReader) {
    return This->lpVtbl->CreateDataReader(This,inputStream,dataReader);
}
#endif
#ifdef WIDL_using_Windows_Storage_Streams
#define IID_IDataReaderFactory IID___x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory
#define IDataReaderFactoryVtbl __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactoryVtbl
#define IDataReaderFactory __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory
#define IDataReaderFactory_QueryInterface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_QueryInterface
#define IDataReaderFactory_AddRef __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_AddRef
#define IDataReaderFactory_Release __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_Release
#define IDataReaderFactory_GetIids __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetIids
#define IDataReaderFactory_GetRuntimeClassName __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetRuntimeClassName
#define IDataReaderFactory_GetTrustLevel __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_GetTrustLevel
#define IDataReaderFactory_CreateDataReader __x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_CreateDataReader
#endif /* WIDL_using_Windows_Storage_Streams */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderFactory_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IDataReaderStatics interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics, 0x11fcbfc8, 0xf93a, 0x471b, 0xb1,0x21, 0xf3,0x79,0xe3,0x49,0x31,0x3c);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Storage {
            namespace Streams {
                MIDL_INTERFACE("11fcbfc8-f93a-471b-b121-f379e349313c")
                IDataReaderStatics : public IInspectable
                {
                    virtual HRESULT STDMETHODCALLTYPE FromBuffer(
                        ABI::Windows::Storage::Streams::IBuffer *buffer,
                        ABI::Windows::Storage::Streams::IDataReader **dataReader) = 0;

                };
            }
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics, 0x11fcbfc8, 0xf93a, 0x471b, 0xb1,0x21, 0xf3,0x79,0xe3,0x49,0x31,0x3c)
#endif
#else
typedef struct __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStaticsVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This,
        TrustLevel *trustLevel);

    /*** IDataReaderStatics methods ***/
    HRESULT (STDMETHODCALLTYPE *FromBuffer)(
        __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics *This,
        __x_ABI_CWindows_CStorage_CStreams_CIBuffer *buffer,
        __x_ABI_CWindows_CStorage_CStreams_CIDataReader **dataReader);

    END_INTERFACE
} __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStaticsVtbl;

interface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics {
    CONST_VTBL __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStaticsVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IDataReaderStatics methods ***/
#define __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FromBuffer(This,buffer,dataReader) (This)->lpVtbl->FromBuffer(This,buffer,dataReader)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_QueryInterface(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_AddRef(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_Release(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetIids(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetRuntimeClassName(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetTrustLevel(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IDataReaderStatics methods ***/
static inline HRESULT __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FromBuffer(__x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics* This,__x_ABI_CWindows_CStorage_CStreams_CIBuffer *buffer,__x_ABI_CWindows_CStorage_CStreams_CIDataReader **dataReader) {
    return This->lpVtbl->FromBuffer(This,buffer,dataReader);
}
#endif
#ifdef WIDL_using_Windows_Storage_Streams
#define IID_IDataReaderStatics IID___x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics
#define IDataReaderStaticsVtbl __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStaticsVtbl
#define IDataReaderStatics __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics
#define IDataReaderStatics_QueryInterface __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_QueryInterface
#define IDataReaderStatics_AddRef __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_AddRef
#define IDataReaderStatics_Release __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_Release
#define IDataReaderStatics_GetIids __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetIids
#define IDataReaderStatics_GetRuntimeClassName __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetRuntimeClassName
#define IDataReaderStatics_GetTrustLevel __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_GetTrustLevel
#define IDataReaderStatics_FromBuffer __x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_FromBuffer
#endif /* WIDL_using_Windows_Storage_Streams */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CStorage_CStreams_CIDataReaderStatics_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Storage.Streams.DataReader
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Storage_Streams_DataReader_DEFINED
#define RUNTIMECLASS_Windows_Storage_Streams_DataReader_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Storage_Streams_DataReader[] = {'W','i','n','d','o','w','s','.','S','t','o','r','a','g','e','.','S','t','r','e','a','m','s','.','D','a','t','a','R','e','a','d','e','r',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Storage_Streams_DataReader[] = L"Windows.Storage.Streams.DataReader";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Storage_Streams_DataReader[] = {'W','i','n','d','o','w','s','.','S','t','o','r','a','g','e','.','S','t','r','e','a','m','s','.','D','a','t','a','R','e','a','d','e','r',0};
#endif
#endif /* RUNTIMECLASS_Windows_Storage_Streams_DataReader_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.Storage.Streams.DataReaderLoadOperation
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_Storage_Streams_DataReaderLoadOperation_DEFINED
#define RUNTIMECLASS_Windows_Storage_Streams_DataReaderLoadOperation_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_Storage_Streams_DataReaderLoadOperation[] = {'W','i','n','d','o','w','s','.','S','t','o','r','a','g','e','.','S','t','r','e','a','m','s','.','D','a','t','a','R','e','a','d','e','r','L','o','a','d','O','p','e','r','a','t','i','o','n',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Storage_Streams_DataReaderLoadOperation[] = L"Windows.Storage.Streams.DataReaderLoadOperation";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_Storage_Streams_DataReaderLoadOperation[] = {'W','i','n','d','o','w','s','.','S','t','o','r','a','g','e','.','S','t','r','e','a','m','s','.','D','a','t','a','R','e','a','d','e','r','L','o','a','d','O','p','e','r','a','t','i','o','n',0};
#endif
#endif /* RUNTIMECLASS_Windows_Storage_Streams_DataReaderLoadOperation_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HSTRING_UserSize     (ULONG *, ULONG, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserMarshal  (ULONG *, unsigned char *, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserUnmarshal(ULONG *, unsigned char *, HSTRING *);
void            __RPC_USER HSTRING_UserFree     (ULONG *, HSTRING *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __windows_storage_streams_ext_h__ */
