/*** Autogenerated by WIDL 10.9 from /var/folders/gg/ft360_357zjct4wzf6_ff6g80000gn/T/tmp.oUGlZhdQrR/windows.system_ext.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __windows_system_ext_h__
#define __windows_system_ext_h__

/* Forward declarations */

#ifndef ____x_ABI_CWindows_CSystem_CLauncherOptions_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CLauncherOptions_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace System {
            class LauncherOptions;
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CSystem_CLauncherOptions __x_ABI_CWindows_CSystem_CLauncherOptions;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CSystem_CLauncherOptions_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILaunchUriResult __x_ABI_CWindows_CSystem_CILaunchUriResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILaunchUriResult ABI::Windows::System::ILaunchUriResult
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILaunchUriResult;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CLaunchUriResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CLaunchUriResult_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace System {
            class LaunchUriResult;
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CSystem_CLaunchUriResult __x_ABI_CWindows_CSystem_CLaunchUriResult;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CSystem_CLaunchUriResult_FWD_DEFINED__ */

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics4 __x_ABI_CWindows_CSystem_CILauncherStatics4;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics4 ABI::Windows::System::ILauncherStatics4
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics4;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CLauncher_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CLauncher_FWD_DEFINED__
#ifdef __cplusplus
namespace ABI {
    namespace Windows {
        namespace System {
            class Launcher;
        }
    }
}
#else
typedef struct __x_ABI_CWindows_CSystem_CLauncher __x_ABI_CWindows_CSystem_CLauncher;
#endif /* defined __cplusplus */
#endif /* defined ____x_ABI_CWindows_CSystem_CLauncher_FWD_DEFINED__ */

#ifndef ____FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_FWD_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_FWD_DEFINED__
typedef interface __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus;
#ifdef __cplusplus
#define __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus ABI::Windows::Foundation::IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperationCompletedHandler_1_LaunchUriStatus_FWD_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_LaunchUriStatus_FWD_DEFINED__
typedef interface __FIAsyncOperationCompletedHandler_1_LaunchUriStatus __FIAsyncOperationCompletedHandler_1_LaunchUriStatus;
#ifdef __cplusplus
#define __FIAsyncOperationCompletedHandler_1_LaunchUriStatus ABI::Windows::Foundation::IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
typedef interface __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult;
#ifdef __cplusplus
#define __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult ABI::Windows::Foundation::IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
#define ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult;
#ifdef __cplusplus
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_LaunchUriStatus_FWD_DEFINED__
#define ____FIAsyncOperation_1_LaunchUriStatus_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_LaunchUriStatus __FIAsyncOperation_1_LaunchUriStatus;
#ifdef __cplusplus
#define __FIAsyncOperation_1_LaunchUriStatus ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriStatus >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_LaunchQuerySupportStatus_FWD_DEFINED__
#define ____FIAsyncOperation_1_LaunchQuerySupportStatus_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_LaunchQuerySupportStatus __FIAsyncOperation_1_LaunchQuerySupportStatus;
#ifdef __cplusplus
#define __FIAsyncOperation_1_LaunchQuerySupportStatus ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus >
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <inspectable.h>
#include <asyncinfo.h>
#include <eventtoken.h>
#include <windowscontracts.h>
#include <windows.foundation.h>
#include <windows.applicationmodel.h>
#include <windows.system.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifndef __cplusplus
typedef enum __x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus __x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus;
#endif /* __cplusplus */

#ifndef __cplusplus
typedef enum __x_ABI_CWindows_CSystem_CLaunchUriStatus __x_ABI_CWindows_CSystem_CLaunchUriStatus;
#endif /* __cplusplus */

#ifndef ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILaunchUriResult __x_ABI_CWindows_CSystem_CILaunchUriResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILaunchUriResult ABI::Windows::System::ILaunchUriResult
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILaunchUriResult;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherOptions_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherOptions_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherOptions __x_ABI_CWindows_CSystem_CILauncherOptions;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherOptions ABI::Windows::System::ILauncherOptions
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherOptions;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CIUser_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CIUser_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CIUser __x_ABI_CWindows_CSystem_CIUser;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CIUser ABI::Windows::System::IUser
namespace ABI {
    namespace Windows {
        namespace System {
            interface IUser;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics __x_ABI_CWindows_CSystem_CILauncherStatics;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics ABI::Windows::System::ILauncherStatics
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics2_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics2_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics2 __x_ABI_CWindows_CSystem_CILauncherStatics2;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics2 ABI::Windows::System::ILauncherStatics2
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics2;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics3_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics3_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics3 __x_ABI_CWindows_CSystem_CILauncherStatics3;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics3 ABI::Windows::System::ILauncherStatics3
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics3;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics4 __x_ABI_CWindows_CSystem_CILauncherStatics4;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics4 ABI::Windows::System::ILauncherStatics4
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics4;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics5_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics5_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics5 __x_ABI_CWindows_CSystem_CILauncherStatics5;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics5 ABI::Windows::System::ILauncherStatics5
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics5;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILaunchUriResult_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILaunchUriResult __x_ABI_CWindows_CSystem_CILaunchUriResult;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILaunchUriResult ABI::Windows::System::ILaunchUriResult
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILaunchUriResult;
        }
    }
}
#endif /* __cplusplus */
#endif

#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics4_FWD_DEFINED__
typedef interface __x_ABI_CWindows_CSystem_CILauncherStatics4 __x_ABI_CWindows_CSystem_CILauncherStatics4;
#ifdef __cplusplus
#define __x_ABI_CWindows_CSystem_CILauncherStatics4 ABI::Windows::System::ILauncherStatics4
namespace ABI {
    namespace Windows {
        namespace System {
            interface ILauncherStatics4;
        }
    }
}
#endif /* __cplusplus */
#endif

/*
 * Class Windows.System.LauncherOptions
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_System_LauncherOptions_DEFINED
#define RUNTIMECLASS_Windows_System_LauncherOptions_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_System_LauncherOptions[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','e','r','O','p','t','i','o','n','s',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_LauncherOptions[] = L"Windows.System.LauncherOptions";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_LauncherOptions[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','e','r','O','p','t','i','o','n','s',0};
#endif
#endif /* RUNTIMECLASS_Windows_System_LauncherOptions_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifdef __cplusplus
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace System {
            enum LaunchQuerySupportStatus {
                LaunchQuerySupportStatus_Available = 0,
                LaunchQuerySupportStatus_AppNotInstalled = 1,
                LaunchQuerySupportStatus_AppUnavailable = 2,
                LaunchQuerySupportStatus_NotSupported = 3,
                LaunchQuerySupportStatus_Unknown = 4
            };
        }
    }
}
extern "C" {
#else
enum __x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus {
    LaunchQuerySupportStatus_Available = 0,
    LaunchQuerySupportStatus_AppNotInstalled = 1,
    LaunchQuerySupportStatus_AppUnavailable = 2,
    LaunchQuerySupportStatus_NotSupported = 3,
    LaunchQuerySupportStatus_Unknown = 4
};
#ifdef WIDL_using_Windows_System
#define LaunchQuerySupportStatus __x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus
#endif /* WIDL_using_Windows_System */
#endif

#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifdef __cplusplus
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace System {
            enum LaunchUriStatus {
                LaunchUriStatus_Success = 0,
                LaunchUriStatus_AppUnavailable = 1,
                LaunchUriStatus_ProtocolUnavailable = 2,
                LaunchUriStatus_Unknown = 3
            };
        }
    }
}
extern "C" {
#else
enum __x_ABI_CWindows_CSystem_CLaunchUriStatus {
    LaunchUriStatus_Success = 0,
    LaunchUriStatus_AppUnavailable = 1,
    LaunchUriStatus_ProtocolUnavailable = 2,
    LaunchUriStatus_Unknown = 3
};
#ifdef WIDL_using_Windows_System
#define LaunchUriStatus __x_ABI_CWindows_CSystem_CLaunchUriStatus
#endif /* WIDL_using_Windows_System */
#endif

#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */
#ifndef ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
#define ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult;
#ifdef __cplusplus
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriResult* >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_LaunchUriStatus_FWD_DEFINED__
#define ____FIAsyncOperation_1_LaunchUriStatus_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_LaunchUriStatus __FIAsyncOperation_1_LaunchUriStatus;
#ifdef __cplusplus
#define __FIAsyncOperation_1_LaunchUriStatus ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriStatus >
#endif /* __cplusplus */
#endif

#ifndef ____FIAsyncOperation_1_LaunchQuerySupportStatus_FWD_DEFINED__
#define ____FIAsyncOperation_1_LaunchQuerySupportStatus_FWD_DEFINED__
typedef interface __FIAsyncOperation_1_LaunchQuerySupportStatus __FIAsyncOperation_1_LaunchQuerySupportStatus;
#ifdef __cplusplus
#define __FIAsyncOperation_1_LaunchQuerySupportStatus ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus >
#endif /* __cplusplus */
#endif

/*****************************************************************************
 * ILaunchUriResult interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef ____x_ABI_CWindows_CSystem_CILaunchUriResult_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILaunchUriResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CSystem_CILaunchUriResult, 0xec27a8df, 0xf6d5, 0x45ca, 0x91,0x3a, 0x70,0xa4,0x0c,0x5c,0x82,0x21);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace System {
            MIDL_INTERFACE("ec27a8df-f6d5-45ca-913a-70a40c5c8221")
            ILaunchUriResult : public IInspectable
            {
                virtual HRESULT STDMETHODCALLTYPE get_Status(
                    ABI::Windows::System::LaunchUriStatus *value) = 0;

                virtual HRESULT STDMETHODCALLTYPE get_Result(
                    ABI::Windows::Foundation::Collections::IPropertySet **value) = 0;

            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CSystem_CILaunchUriResult, 0xec27a8df, 0xf6d5, 0x45ca, 0x91,0x3a, 0x70,0xa4,0x0c,0x5c,0x82,0x21)
#endif
#else
typedef struct __x_ABI_CWindows_CSystem_CILaunchUriResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        TrustLevel *trustLevel);

    /*** ILaunchUriResult methods ***/
    HRESULT (STDMETHODCALLTYPE *get_Status)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        __x_ABI_CWindows_CSystem_CLaunchUriStatus *value);

    HRESULT (STDMETHODCALLTYPE *get_Result)(
        __x_ABI_CWindows_CSystem_CILaunchUriResult *This,
        __x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **value);

    END_INTERFACE
} __x_ABI_CWindows_CSystem_CILaunchUriResultVtbl;

interface __x_ABI_CWindows_CSystem_CILaunchUriResult {
    CONST_VTBL __x_ABI_CWindows_CSystem_CILaunchUriResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** ILaunchUriResult methods ***/
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Status(This,value) (This)->lpVtbl->get_Status(This,value)
#define __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Result(This,value) (This)->lpVtbl->get_Result(This,value)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_QueryInterface(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CSystem_CILaunchUriResult_AddRef(__x_ABI_CWindows_CSystem_CILaunchUriResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CSystem_CILaunchUriResult_Release(__x_ABI_CWindows_CSystem_CILaunchUriResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_GetIids(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_GetRuntimeClassName(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_GetTrustLevel(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** ILaunchUriResult methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Status(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,__x_ABI_CWindows_CSystem_CLaunchUriStatus *value) {
    return This->lpVtbl->get_Status(This,value);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Result(__x_ABI_CWindows_CSystem_CILaunchUriResult* This,__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet **value) {
    return This->lpVtbl->get_Result(This,value);
}
#endif
#ifdef WIDL_using_Windows_System
#define IID_ILaunchUriResult IID___x_ABI_CWindows_CSystem_CILaunchUriResult
#define ILaunchUriResultVtbl __x_ABI_CWindows_CSystem_CILaunchUriResultVtbl
#define ILaunchUriResult __x_ABI_CWindows_CSystem_CILaunchUriResult
#define ILaunchUriResult_QueryInterface __x_ABI_CWindows_CSystem_CILaunchUriResult_QueryInterface
#define ILaunchUriResult_AddRef __x_ABI_CWindows_CSystem_CILaunchUriResult_AddRef
#define ILaunchUriResult_Release __x_ABI_CWindows_CSystem_CILaunchUriResult_Release
#define ILaunchUriResult_GetIids __x_ABI_CWindows_CSystem_CILaunchUriResult_GetIids
#define ILaunchUriResult_GetRuntimeClassName __x_ABI_CWindows_CSystem_CILaunchUriResult_GetRuntimeClassName
#define ILaunchUriResult_GetTrustLevel __x_ABI_CWindows_CSystem_CILaunchUriResult_GetTrustLevel
#define ILaunchUriResult_get_Status __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Status
#define ILaunchUriResult_get_Result __x_ABI_CWindows_CSystem_CILaunchUriResult_get_Result
#endif /* WIDL_using_Windows_System */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CSystem_CILaunchUriResult_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*
 * Class Windows.System.LaunchUriResult
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_System_LaunchUriResult_DEFINED
#define RUNTIMECLASS_Windows_System_LaunchUriResult_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_System_LaunchUriResult[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','U','r','i','R','e','s','u','l','t',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_LaunchUriResult[] = L"Windows.System.LaunchUriResult";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_LaunchUriResult[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','U','r','i','R','e','s','u','l','t',0};
#endif
#endif /* RUNTIMECLASS_Windows_System_LaunchUriResult_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * ILauncherStatics4 interface
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x30000
#ifndef ____x_ABI_CWindows_CSystem_CILauncherStatics4_INTERFACE_DEFINED__
#define ____x_ABI_CWindows_CSystem_CILauncherStatics4_INTERFACE_DEFINED__

DEFINE_GUID(IID___x_ABI_CWindows_CSystem_CILauncherStatics4, 0xb9ec819f, 0xb5a5, 0x41c6, 0xb3,0xb3, 0xdd,0x1b,0x31,0x78,0xbc,0xf2);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace System {
            MIDL_INTERFACE("b9ec819f-b5a5-41c6-b3b3-dd1b3178bcf2")
            ILauncherStatics4 : public IInspectable
            {
                virtual HRESULT STDMETHODCALLTYPE QueryAppUriSupportAsync(
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE QueryAppUriSupportWithPackageFamilyNameAsync(
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    HSTRING packageFamilyName,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE FindAppUriHandlersAsync(
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::Foundation::Collections::IVectorView<ABI::Windows::ApplicationModel::AppInfo* >* > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE LaunchUriForUserAsync(
                    ABI::Windows::System::IUser *user,
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriStatus > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE LaunchUriWithOptionsForUserAsync(
                    ABI::Windows::System::IUser *user,
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::System::ILauncherOptions *options,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriStatus > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE LaunchUriWithDataForUserAsync(
                    ABI::Windows::System::IUser *user,
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::System::ILauncherOptions *options,
                    ABI::Windows::Foundation::Collections::IPropertySet *inputData,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriStatus > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE LaunchUriForResultsForUserAsync(
                    ABI::Windows::System::IUser *user,
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::System::ILauncherOptions *options,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriResult* > **operation) = 0;

                virtual HRESULT STDMETHODCALLTYPE LaunchUriForResultsWithDataForUserAsync(
                    ABI::Windows::System::IUser *user,
                    ABI::Windows::Foundation::IUriRuntimeClass *uri,
                    ABI::Windows::System::ILauncherOptions *options,
                    ABI::Windows::Foundation::Collections::IPropertySet *inputData,
                    ABI::Windows::Foundation::IAsyncOperation<ABI::Windows::System::LaunchUriResult* > **operation) = 0;

            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__x_ABI_CWindows_CSystem_CILauncherStatics4, 0xb9ec819f, 0xb5a5, 0x41c6, 0xb3,0xb3, 0xdd,0x1b,0x31,0x78,0xbc,0xf2)
#endif
#else
typedef struct __x_ABI_CWindows_CSystem_CILauncherStatics4Vtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        TrustLevel *trustLevel);

    /*** ILauncherStatics4 methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryAppUriSupportAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __FIAsyncOperation_1_LaunchQuerySupportStatus **operation);

    HRESULT (STDMETHODCALLTYPE *QueryAppUriSupportWithPackageFamilyNameAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        HSTRING packageFamilyName,
        __FIAsyncOperation_1_LaunchQuerySupportStatus **operation);

    HRESULT (STDMETHODCALLTYPE *FindAppUriHandlersAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __FIAsyncOperation_1___FIVectorView_1_Windows__CApplicationModel__CAppInfo **operation);

    HRESULT (STDMETHODCALLTYPE *LaunchUriForUserAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CSystem_CIUser *user,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __FIAsyncOperation_1_LaunchUriStatus **operation);

    HRESULT (STDMETHODCALLTYPE *LaunchUriWithOptionsForUserAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CSystem_CIUser *user,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __x_ABI_CWindows_CSystem_CILauncherOptions *options,
        __FIAsyncOperation_1_LaunchUriStatus **operation);

    HRESULT (STDMETHODCALLTYPE *LaunchUriWithDataForUserAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CSystem_CIUser *user,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __x_ABI_CWindows_CSystem_CILauncherOptions *options,
        __x_ABI_CWindows_CFoundation_CCollections_CIPropertySet *inputData,
        __FIAsyncOperation_1_LaunchUriStatus **operation);

    HRESULT (STDMETHODCALLTYPE *LaunchUriForResultsForUserAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CSystem_CIUser *user,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __x_ABI_CWindows_CSystem_CILauncherOptions *options,
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult **operation);

    HRESULT (STDMETHODCALLTYPE *LaunchUriForResultsWithDataForUserAsync)(
        __x_ABI_CWindows_CSystem_CILauncherStatics4 *This,
        __x_ABI_CWindows_CSystem_CIUser *user,
        __x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,
        __x_ABI_CWindows_CSystem_CILauncherOptions *options,
        __x_ABI_CWindows_CFoundation_CCollections_CIPropertySet *inputData,
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult **operation);

    END_INTERFACE
} __x_ABI_CWindows_CSystem_CILauncherStatics4Vtbl;

interface __x_ABI_CWindows_CSystem_CILauncherStatics4 {
    CONST_VTBL __x_ABI_CWindows_CSystem_CILauncherStatics4Vtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** ILauncherStatics4 methods ***/
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportAsync(This,uri,operation) (This)->lpVtbl->QueryAppUriSupportAsync(This,uri,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportWithPackageFamilyNameAsync(This,uri,packageFamilyName,operation) (This)->lpVtbl->QueryAppUriSupportWithPackageFamilyNameAsync(This,uri,packageFamilyName,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_FindAppUriHandlersAsync(This,uri,operation) (This)->lpVtbl->FindAppUriHandlersAsync(This,uri,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForUserAsync(This,user,uri,operation) (This)->lpVtbl->LaunchUriForUserAsync(This,user,uri,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithOptionsForUserAsync(This,user,uri,options,operation) (This)->lpVtbl->LaunchUriWithOptionsForUserAsync(This,user,uri,options,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithDataForUserAsync(This,user,uri,options,inputData,operation) (This)->lpVtbl->LaunchUriWithDataForUserAsync(This,user,uri,options,inputData,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsForUserAsync(This,user,uri,options,operation) (This)->lpVtbl->LaunchUriForResultsForUserAsync(This,user,uri,options,operation)
#define __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsWithDataForUserAsync(This,user,uri,options,inputData,operation) (This)->lpVtbl->LaunchUriForResultsWithDataForUserAsync(This,user,uri,options,inputData,operation)
#else
/*** IUnknown methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryInterface(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __x_ABI_CWindows_CSystem_CILauncherStatics4_AddRef(__x_ABI_CWindows_CSystem_CILauncherStatics4* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __x_ABI_CWindows_CSystem_CILauncherStatics4_Release(__x_ABI_CWindows_CSystem_CILauncherStatics4* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_GetIids(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_GetRuntimeClassName(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_GetTrustLevel(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** ILauncherStatics4 methods ***/
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__FIAsyncOperation_1_LaunchQuerySupportStatus **operation) {
    return This->lpVtbl->QueryAppUriSupportAsync(This,uri,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportWithPackageFamilyNameAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,HSTRING packageFamilyName,__FIAsyncOperation_1_LaunchQuerySupportStatus **operation) {
    return This->lpVtbl->QueryAppUriSupportWithPackageFamilyNameAsync(This,uri,packageFamilyName,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_FindAppUriHandlersAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__FIAsyncOperation_1___FIVectorView_1_Windows__CApplicationModel__CAppInfo **operation) {
    return This->lpVtbl->FindAppUriHandlersAsync(This,uri,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForUserAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CSystem_CIUser *user,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__FIAsyncOperation_1_LaunchUriStatus **operation) {
    return This->lpVtbl->LaunchUriForUserAsync(This,user,uri,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithOptionsForUserAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CSystem_CIUser *user,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__x_ABI_CWindows_CSystem_CILauncherOptions *options,__FIAsyncOperation_1_LaunchUriStatus **operation) {
    return This->lpVtbl->LaunchUriWithOptionsForUserAsync(This,user,uri,options,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithDataForUserAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CSystem_CIUser *user,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__x_ABI_CWindows_CSystem_CILauncherOptions *options,__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet *inputData,__FIAsyncOperation_1_LaunchUriStatus **operation) {
    return This->lpVtbl->LaunchUriWithDataForUserAsync(This,user,uri,options,inputData,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsForUserAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CSystem_CIUser *user,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__x_ABI_CWindows_CSystem_CILauncherOptions *options,__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult **operation) {
    return This->lpVtbl->LaunchUriForResultsForUserAsync(This,user,uri,options,operation);
}
static inline HRESULT __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsWithDataForUserAsync(__x_ABI_CWindows_CSystem_CILauncherStatics4* This,__x_ABI_CWindows_CSystem_CIUser *user,__x_ABI_CWindows_CFoundation_CIUriRuntimeClass *uri,__x_ABI_CWindows_CSystem_CILauncherOptions *options,__x_ABI_CWindows_CFoundation_CCollections_CIPropertySet *inputData,__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult **operation) {
    return This->lpVtbl->LaunchUriForResultsWithDataForUserAsync(This,user,uri,options,inputData,operation);
}
#endif
#ifdef WIDL_using_Windows_System
#define IID_ILauncherStatics4 IID___x_ABI_CWindows_CSystem_CILauncherStatics4
#define ILauncherStatics4Vtbl __x_ABI_CWindows_CSystem_CILauncherStatics4Vtbl
#define ILauncherStatics4 __x_ABI_CWindows_CSystem_CILauncherStatics4
#define ILauncherStatics4_QueryInterface __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryInterface
#define ILauncherStatics4_AddRef __x_ABI_CWindows_CSystem_CILauncherStatics4_AddRef
#define ILauncherStatics4_Release __x_ABI_CWindows_CSystem_CILauncherStatics4_Release
#define ILauncherStatics4_GetIids __x_ABI_CWindows_CSystem_CILauncherStatics4_GetIids
#define ILauncherStatics4_GetRuntimeClassName __x_ABI_CWindows_CSystem_CILauncherStatics4_GetRuntimeClassName
#define ILauncherStatics4_GetTrustLevel __x_ABI_CWindows_CSystem_CILauncherStatics4_GetTrustLevel
#define ILauncherStatics4_QueryAppUriSupportAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportAsync
#define ILauncherStatics4_QueryAppUriSupportWithPackageFamilyNameAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_QueryAppUriSupportWithPackageFamilyNameAsync
#define ILauncherStatics4_FindAppUriHandlersAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_FindAppUriHandlersAsync
#define ILauncherStatics4_LaunchUriForUserAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForUserAsync
#define ILauncherStatics4_LaunchUriWithOptionsForUserAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithOptionsForUserAsync
#define ILauncherStatics4_LaunchUriWithDataForUserAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriWithDataForUserAsync
#define ILauncherStatics4_LaunchUriForResultsForUserAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsForUserAsync
#define ILauncherStatics4_LaunchUriForResultsWithDataForUserAsync __x_ABI_CWindows_CSystem_CILauncherStatics4_LaunchUriForResultsWithDataForUserAsync
#endif /* WIDL_using_Windows_System */
#endif

#endif

#endif  /* ____x_ABI_CWindows_CSystem_CILauncherStatics4_INTERFACE_DEFINED__ */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x30000 */

/*
 * Class Windows.System.Launcher
 */
#if WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000
#ifndef RUNTIMECLASS_Windows_System_Launcher_DEFINED
#define RUNTIMECLASS_Windows_System_Launcher_DEFINED
#if !defined(_MSC_VER) && !defined(__MINGW32__)
static const WCHAR RuntimeClass_Windows_System_Launcher[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','e','r',0};
#elif defined(__GNUC__) && !defined(__cplusplus)
const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_Launcher[] = L"Windows.System.Launcher";
#else
extern const DECLSPEC_SELECTANY WCHAR RuntimeClass_Windows_System_Launcher[] = {'W','i','n','d','o','w','s','.','S','y','s','t','e','m','.','L','a','u','n','c','h','e','r',0};
#endif
#endif /* RUNTIMECLASS_Windows_System_Launcher_DEFINED */
#endif /* WINDOWS_FOUNDATION_UNIVERSALAPICONTRACT_VERSION >= 0x10000 */

/*****************************************************************************
 * IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus > interface
 */
#ifndef ____FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus, 0x198cac52, 0xabcd, 0x5529, 0x93,0x3f, 0x07,0x1c,0xc9,0x3f,0xd6,0x35);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("198cac52-abcd-5529-933f-071cc93fd635")
            IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus > : IAsyncOperationCompletedHandler_impl<ABI::Windows::System::LaunchQuerySupportStatus >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus, 0x198cac52, 0xabcd, 0x5529, 0x93,0x3f, 0x07,0x1c,0xc9,0x3f,0xd6,0x35)
#endif
#else
typedef struct __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatusVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *This);

    /*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *This,
        __FIAsyncOperation_1_LaunchQuerySupportStatus *info,
        AsyncStatus status);

    END_INTERFACE
} __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatusVtbl;

interface __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus {
    CONST_VTBL __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatusVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
#define __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Invoke(This,info,status) (This)->lpVtbl->Invoke(This,info,status)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_QueryInterface(__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_AddRef(__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Release(__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Invoke(__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus* This,__FIAsyncOperation_1_LaunchQuerySupportStatus *info,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,info,status);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperationCompletedHandler_LaunchQuerySupportStatus IID___FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatusVtbl __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatusVtbl
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatus __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatus_QueryInterface __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_QueryInterface
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatus_AddRef __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_AddRef
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatus_Release __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Release
#define IAsyncOperationCompletedHandler_LaunchQuerySupportStatus_Invoke __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_Invoke
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus > interface
 */
#ifndef ____FIAsyncOperationCompletedHandler_1_LaunchUriStatus_INTERFACE_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_LaunchUriStatus_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperationCompletedHandler_1_LaunchUriStatus, 0x520aa58e, 0x40d6, 0x5a57, 0xa6,0xdc, 0xcb,0x5f,0xae,0xa5,0xcc,0xa5);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("520aa58e-40d6-5a57-a6dc-cb5faea5cca5")
            IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus > : IAsyncOperationCompletedHandler_impl<ABI::Windows::System::LaunchUriStatus >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperationCompletedHandler_1_LaunchUriStatus, 0x520aa58e, 0x40d6, 0x5a57, 0xa6,0xdc, 0xcb,0x5f,0xae,0xa5,0xcc,0xa5)
#endif
#else
typedef struct __FIAsyncOperationCompletedHandler_1_LaunchUriStatusVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus *This);

    /*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus > methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus *This,
        __FIAsyncOperation_1_LaunchUriStatus *info,
        AsyncStatus status);

    END_INTERFACE
} __FIAsyncOperationCompletedHandler_1_LaunchUriStatusVtbl;

interface __FIAsyncOperationCompletedHandler_1_LaunchUriStatus {
    CONST_VTBL __FIAsyncOperationCompletedHandler_1_LaunchUriStatusVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus > methods ***/
#define __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Invoke(This,info,status) (This)->lpVtbl->Invoke(This,info,status)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_QueryInterface(__FIAsyncOperationCompletedHandler_1_LaunchUriStatus* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_AddRef(__FIAsyncOperationCompletedHandler_1_LaunchUriStatus* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Release(__FIAsyncOperationCompletedHandler_1_LaunchUriStatus* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriStatus > methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Invoke(__FIAsyncOperationCompletedHandler_1_LaunchUriStatus* This,__FIAsyncOperation_1_LaunchUriStatus *info,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,info,status);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperationCompletedHandler_LaunchUriStatus IID___FIAsyncOperationCompletedHandler_1_LaunchUriStatus
#define IAsyncOperationCompletedHandler_LaunchUriStatusVtbl __FIAsyncOperationCompletedHandler_1_LaunchUriStatusVtbl
#define IAsyncOperationCompletedHandler_LaunchUriStatus __FIAsyncOperationCompletedHandler_1_LaunchUriStatus
#define IAsyncOperationCompletedHandler_LaunchUriStatus_QueryInterface __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_QueryInterface
#define IAsyncOperationCompletedHandler_LaunchUriStatus_AddRef __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_AddRef
#define IAsyncOperationCompletedHandler_LaunchUriStatus_Release __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Release
#define IAsyncOperationCompletedHandler_LaunchUriStatus_Invoke __FIAsyncOperationCompletedHandler_1_LaunchUriStatus_Invoke
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperationCompletedHandler_1_LaunchUriStatus_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* > interface
 */
#ifndef ____FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__
#define ____FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult, 0x70a97bf8, 0xe0a5, 0x59bb, 0x91,0x74, 0x81,0x2a,0x13,0x1d,0x85,0xa0);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("70a97bf8-e0a5-59bb-9174-812a131d85a0")
            IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* > : IAsyncOperationCompletedHandler_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::System::LaunchUriResult*, ABI::Windows::System::ILaunchUriResult* > >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult, 0x70a97bf8, 0xe0a5, 0x59bb, 0x91,0x74, 0x81,0x2a,0x13,0x1d,0x85,0xa0)
#endif
#else
typedef struct __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *This);

    /*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* > methods ***/
    HRESULT (STDMETHODCALLTYPE *Invoke)(
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *This,
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *info,
        AsyncStatus status);

    END_INTERFACE
} __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResultVtbl;

interface __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult {
    CONST_VTBL __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Release(This) (This)->lpVtbl->Release(This)
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* > methods ***/
#define __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Invoke(This,info,status) (This)->lpVtbl->Invoke(This,info,status)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_QueryInterface(__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_AddRef(__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Release(__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IAsyncOperationCompletedHandler<ABI::Windows::System::LaunchUriResult* > methods ***/
static inline HRESULT __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Invoke(__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult* This,__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *info,AsyncStatus status) {
    return This->lpVtbl->Invoke(This,info,status);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperationCompletedHandler_LaunchUriResult IID___FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult
#define IAsyncOperationCompletedHandler_LaunchUriResultVtbl __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResultVtbl
#define IAsyncOperationCompletedHandler_LaunchUriResult __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult
#define IAsyncOperationCompletedHandler_LaunchUriResult_QueryInterface __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_QueryInterface
#define IAsyncOperationCompletedHandler_LaunchUriResult_AddRef __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_AddRef
#define IAsyncOperationCompletedHandler_LaunchUriResult_Release __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Release
#define IAsyncOperationCompletedHandler_LaunchUriResult_Invoke __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_Invoke
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperation<ABI::Windows::System::LaunchUriResult* > interface
 */
#ifndef ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__
#define ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult, 0x7f97fc15, 0x1cd6, 0x54b7, 0xa2,0x90, 0xac,0xb6,0x0d,0xba,0x81,0xa1);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("7f97fc15-1cd6-54b7-a290-acb60dba81a1")
            IAsyncOperation<ABI::Windows::System::LaunchUriResult* > : IAsyncOperation_impl<ABI::Windows::Foundation::Internal::AggregateType<ABI::Windows::System::LaunchUriResult*, ABI::Windows::System::ILaunchUriResult* > >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult, 0x7f97fc15, 0x1cd6, 0x54b7, 0xa2,0x90, 0xac,0xb6,0x0d,0xba,0x81,0xa1)
#endif
#else
typedef struct __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResultVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        TrustLevel *trustLevel);

    /*** IAsyncOperation<ABI::Windows::System::LaunchUriResult* > methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        __FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult **handler);

    HRESULT (STDMETHODCALLTYPE *GetResults)(
        __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult *This,
        __x_ABI_CWindows_CSystem_CILaunchUriResult **results);

    END_INTERFACE
} __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResultVtbl;

interface __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult {
    CONST_VTBL __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResultVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IAsyncOperation<ABI::Windows::System::LaunchUriResult* > methods ***/
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetResults(This,results) (This)->lpVtbl->GetResults(This,results)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_QueryInterface(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_AddRef(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_Release(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetIids(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetRuntimeClassName(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetTrustLevel(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IAsyncOperation<ABI::Windows::System::LaunchUriResult* > methods ***/
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_put_Completed(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_get_Completed(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,__FIAsyncOperationCompletedHandler_1_Windows__CSystem__CLaunchUriResult **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetResults(__FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult* This,__x_ABI_CWindows_CSystem_CILaunchUriResult **results) {
    return This->lpVtbl->GetResults(This,results);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperation_LaunchUriResult IID___FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult
#define IAsyncOperation_LaunchUriResultVtbl __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResultVtbl
#define IAsyncOperation_LaunchUriResult __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult
#define IAsyncOperation_LaunchUriResult_QueryInterface __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_QueryInterface
#define IAsyncOperation_LaunchUriResult_AddRef __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_AddRef
#define IAsyncOperation_LaunchUriResult_Release __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_Release
#define IAsyncOperation_LaunchUriResult_GetIids __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetIids
#define IAsyncOperation_LaunchUriResult_GetRuntimeClassName __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetRuntimeClassName
#define IAsyncOperation_LaunchUriResult_GetTrustLevel __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetTrustLevel
#define IAsyncOperation_LaunchUriResult_put_Completed __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_put_Completed
#define IAsyncOperation_LaunchUriResult_get_Completed __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_get_Completed
#define IAsyncOperation_LaunchUriResult_GetResults __FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_GetResults
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperation_1_Windows__CSystem__CLaunchUriResult_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperation<ABI::Windows::System::LaunchUriStatus > interface
 */
#ifndef ____FIAsyncOperation_1_LaunchUriStatus_INTERFACE_DEFINED__
#define ____FIAsyncOperation_1_LaunchUriStatus_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperation_1_LaunchUriStatus, 0xab3d721b, 0xa4f3, 0x5861, 0xb0,0x34, 0x03,0x0b,0x15,0x23,0x3c,0x52);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("ab3d721b-a4f3-5861-b034-030b15233c52")
            IAsyncOperation<ABI::Windows::System::LaunchUriStatus > : IAsyncOperation_impl<ABI::Windows::System::LaunchUriStatus >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperation_1_LaunchUriStatus, 0xab3d721b, 0xa4f3, 0x5861, 0xb0,0x34, 0x03,0x0b,0x15,0x23,0x3c,0x52)
#endif
#else
typedef struct __FIAsyncOperation_1_LaunchUriStatusVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperation_1_LaunchUriStatus *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperation_1_LaunchUriStatus *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        TrustLevel *trustLevel);

    /*** IAsyncOperation<ABI::Windows::System::LaunchUriStatus > methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        __FIAsyncOperationCompletedHandler_1_LaunchUriStatus **handler);

    HRESULT (STDMETHODCALLTYPE *GetResults)(
        __FIAsyncOperation_1_LaunchUriStatus *This,
        __x_ABI_CWindows_CSystem_CLaunchUriStatus *results);

    END_INTERFACE
} __FIAsyncOperation_1_LaunchUriStatusVtbl;

interface __FIAsyncOperation_1_LaunchUriStatus {
    CONST_VTBL __FIAsyncOperation_1_LaunchUriStatusVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperation_1_LaunchUriStatus_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperation_1_LaunchUriStatus_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperation_1_LaunchUriStatus_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIAsyncOperation_1_LaunchUriStatus_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIAsyncOperation_1_LaunchUriStatus_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIAsyncOperation_1_LaunchUriStatus_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IAsyncOperation<ABI::Windows::System::LaunchUriStatus > methods ***/
#define __FIAsyncOperation_1_LaunchUriStatus_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __FIAsyncOperation_1_LaunchUriStatus_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __FIAsyncOperation_1_LaunchUriStatus_GetResults(This,results) (This)->lpVtbl->GetResults(This,results)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_QueryInterface(__FIAsyncOperation_1_LaunchUriStatus* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperation_1_LaunchUriStatus_AddRef(__FIAsyncOperation_1_LaunchUriStatus* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperation_1_LaunchUriStatus_Release(__FIAsyncOperation_1_LaunchUriStatus* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_GetIids(__FIAsyncOperation_1_LaunchUriStatus* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_GetRuntimeClassName(__FIAsyncOperation_1_LaunchUriStatus* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_GetTrustLevel(__FIAsyncOperation_1_LaunchUriStatus* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IAsyncOperation<ABI::Windows::System::LaunchUriStatus > methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_put_Completed(__FIAsyncOperation_1_LaunchUriStatus* This,__FIAsyncOperationCompletedHandler_1_LaunchUriStatus *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_get_Completed(__FIAsyncOperation_1_LaunchUriStatus* This,__FIAsyncOperationCompletedHandler_1_LaunchUriStatus **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_LaunchUriStatus_GetResults(__FIAsyncOperation_1_LaunchUriStatus* This,__x_ABI_CWindows_CSystem_CLaunchUriStatus *results) {
    return This->lpVtbl->GetResults(This,results);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperation_LaunchUriStatus IID___FIAsyncOperation_1_LaunchUriStatus
#define IAsyncOperation_LaunchUriStatusVtbl __FIAsyncOperation_1_LaunchUriStatusVtbl
#define IAsyncOperation_LaunchUriStatus __FIAsyncOperation_1_LaunchUriStatus
#define IAsyncOperation_LaunchUriStatus_QueryInterface __FIAsyncOperation_1_LaunchUriStatus_QueryInterface
#define IAsyncOperation_LaunchUriStatus_AddRef __FIAsyncOperation_1_LaunchUriStatus_AddRef
#define IAsyncOperation_LaunchUriStatus_Release __FIAsyncOperation_1_LaunchUriStatus_Release
#define IAsyncOperation_LaunchUriStatus_GetIids __FIAsyncOperation_1_LaunchUriStatus_GetIids
#define IAsyncOperation_LaunchUriStatus_GetRuntimeClassName __FIAsyncOperation_1_LaunchUriStatus_GetRuntimeClassName
#define IAsyncOperation_LaunchUriStatus_GetTrustLevel __FIAsyncOperation_1_LaunchUriStatus_GetTrustLevel
#define IAsyncOperation_LaunchUriStatus_put_Completed __FIAsyncOperation_1_LaunchUriStatus_put_Completed
#define IAsyncOperation_LaunchUriStatus_get_Completed __FIAsyncOperation_1_LaunchUriStatus_get_Completed
#define IAsyncOperation_LaunchUriStatus_GetResults __FIAsyncOperation_1_LaunchUriStatus_GetResults
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperation_1_LaunchUriStatus_INTERFACE_DEFINED__ */

/*****************************************************************************
 * IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > interface
 */
#ifndef ____FIAsyncOperation_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__
#define ____FIAsyncOperation_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__

DEFINE_GUID(IID___FIAsyncOperation_1_LaunchQuerySupportStatus, 0xe7539992, 0x2220, 0x5d2d, 0x82,0xc4, 0x3d,0x44,0xf8,0x75,0x0d,0x91);
#if defined(__cplusplus) && !defined(CINTERFACE)
} /* extern "C" */
namespace ABI {
    namespace Windows {
        namespace Foundation {
            template<>
            MIDL_INTERFACE("e7539992-2220-5d2d-82c4-3d44f8750d91")
            IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > : IAsyncOperation_impl<ABI::Windows::System::LaunchQuerySupportStatus >
            {
            };
        }
    }
}
extern "C" {
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(__FIAsyncOperation_1_LaunchQuerySupportStatus, 0xe7539992, 0x2220, 0x5d2d, 0x82,0xc4, 0x3d,0x44,0xf8,0x75,0x0d,0x91)
#endif
#else
typedef struct __FIAsyncOperation_1_LaunchQuerySupportStatusVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This);

    /*** IInspectable methods ***/
    HRESULT (STDMETHODCALLTYPE *GetIids)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        ULONG *iidCount,
        IID **iids);

    HRESULT (STDMETHODCALLTYPE *GetRuntimeClassName)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        HSTRING *className);

    HRESULT (STDMETHODCALLTYPE *GetTrustLevel)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        TrustLevel *trustLevel);

    /*** IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
    HRESULT (STDMETHODCALLTYPE *put_Completed)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *handler);

    HRESULT (STDMETHODCALLTYPE *get_Completed)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        __FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus **handler);

    HRESULT (STDMETHODCALLTYPE *GetResults)(
        __FIAsyncOperation_1_LaunchQuerySupportStatus *This,
        __x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus *results);

    END_INTERFACE
} __FIAsyncOperation_1_LaunchQuerySupportStatusVtbl;

interface __FIAsyncOperation_1_LaunchQuerySupportStatus {
    CONST_VTBL __FIAsyncOperation_1_LaunchQuerySupportStatusVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_AddRef(This) (This)->lpVtbl->AddRef(This)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_Release(This) (This)->lpVtbl->Release(This)
/*** IInspectable methods ***/
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_GetIids(This,iidCount,iids) (This)->lpVtbl->GetIids(This,iidCount,iids)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_GetRuntimeClassName(This,className) (This)->lpVtbl->GetRuntimeClassName(This,className)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_GetTrustLevel(This,trustLevel) (This)->lpVtbl->GetTrustLevel(This,trustLevel)
/*** IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_put_Completed(This,handler) (This)->lpVtbl->put_Completed(This,handler)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_get_Completed(This,handler) (This)->lpVtbl->get_Completed(This,handler)
#define __FIAsyncOperation_1_LaunchQuerySupportStatus_GetResults(This,results) (This)->lpVtbl->GetResults(This,results)
#else
/*** IUnknown methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_QueryInterface(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static inline ULONG __FIAsyncOperation_1_LaunchQuerySupportStatus_AddRef(__FIAsyncOperation_1_LaunchQuerySupportStatus* This) {
    return This->lpVtbl->AddRef(This);
}
static inline ULONG __FIAsyncOperation_1_LaunchQuerySupportStatus_Release(__FIAsyncOperation_1_LaunchQuerySupportStatus* This) {
    return This->lpVtbl->Release(This);
}
/*** IInspectable methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_GetIids(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,ULONG *iidCount,IID **iids) {
    return This->lpVtbl->GetIids(This,iidCount,iids);
}
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_GetRuntimeClassName(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,HSTRING *className) {
    return This->lpVtbl->GetRuntimeClassName(This,className);
}
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_GetTrustLevel(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,TrustLevel *trustLevel) {
    return This->lpVtbl->GetTrustLevel(This,trustLevel);
}
/*** IAsyncOperation<ABI::Windows::System::LaunchQuerySupportStatus > methods ***/
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_put_Completed(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus *handler) {
    return This->lpVtbl->put_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_get_Completed(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,__FIAsyncOperationCompletedHandler_1_LaunchQuerySupportStatus **handler) {
    return This->lpVtbl->get_Completed(This,handler);
}
static inline HRESULT __FIAsyncOperation_1_LaunchQuerySupportStatus_GetResults(__FIAsyncOperation_1_LaunchQuerySupportStatus* This,__x_ABI_CWindows_CSystem_CLaunchQuerySupportStatus *results) {
    return This->lpVtbl->GetResults(This,results);
}
#endif
#ifdef WIDL_using_Windows_Foundation
#define IID_IAsyncOperation_LaunchQuerySupportStatus IID___FIAsyncOperation_1_LaunchQuerySupportStatus
#define IAsyncOperation_LaunchQuerySupportStatusVtbl __FIAsyncOperation_1_LaunchQuerySupportStatusVtbl
#define IAsyncOperation_LaunchQuerySupportStatus __FIAsyncOperation_1_LaunchQuerySupportStatus
#define IAsyncOperation_LaunchQuerySupportStatus_QueryInterface __FIAsyncOperation_1_LaunchQuerySupportStatus_QueryInterface
#define IAsyncOperation_LaunchQuerySupportStatus_AddRef __FIAsyncOperation_1_LaunchQuerySupportStatus_AddRef
#define IAsyncOperation_LaunchQuerySupportStatus_Release __FIAsyncOperation_1_LaunchQuerySupportStatus_Release
#define IAsyncOperation_LaunchQuerySupportStatus_GetIids __FIAsyncOperation_1_LaunchQuerySupportStatus_GetIids
#define IAsyncOperation_LaunchQuerySupportStatus_GetRuntimeClassName __FIAsyncOperation_1_LaunchQuerySupportStatus_GetRuntimeClassName
#define IAsyncOperation_LaunchQuerySupportStatus_GetTrustLevel __FIAsyncOperation_1_LaunchQuerySupportStatus_GetTrustLevel
#define IAsyncOperation_LaunchQuerySupportStatus_put_Completed __FIAsyncOperation_1_LaunchQuerySupportStatus_put_Completed
#define IAsyncOperation_LaunchQuerySupportStatus_get_Completed __FIAsyncOperation_1_LaunchQuerySupportStatus_get_Completed
#define IAsyncOperation_LaunchQuerySupportStatus_GetResults __FIAsyncOperation_1_LaunchQuerySupportStatus_GetResults
#endif /* WIDL_using_Windows_Foundation */
#endif

#endif

#endif  /* ____FIAsyncOperation_1_LaunchQuerySupportStatus_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER HSTRING_UserSize     (ULONG *, ULONG, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserMarshal  (ULONG *, unsigned char *, HSTRING *);
unsigned char * __RPC_USER HSTRING_UserUnmarshal(ULONG *, unsigned char *, HSTRING *);
void            __RPC_USER HSTRING_UserFree     (ULONG *, HSTRING *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __windows_system_ext_h__ */
