// win-arm32 mingw fix (same mechanism as this dir's wincrypt.h/tchar.h).
// llvm-mingw's <tpcshrd.h> (WIDL-autogenerated from tpcshrd.idl) has the tablet
// flick/gesture flags but omits MICROSOFT_TABLETPENSERVICE_PROPERTY, which the real
// Windows SDK (xwin um/tpcshrd.h:68) defines. Chromium's base/win/win_util.cc uses
// it (RemoveProp/SetProp). Include mingw's real header first, then supplement ONLY
// the missing macro, VERBATIM from the SDK. The #ifndef makes it idempotent and
// shadows the SDK copy harmlessly. Matches [[winrt-real-header-integration]].
#include_next <tpcshrd.h>

#ifndef MICROSOFT_TABLETPENSERVICE_PROPERTY
#define MICROSOFT_TABLETPENSERVICE_PROPERTY _T("MicrosoftTabletPenServiceProperty")
#endif
